package availablehammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETAvailablehammersReader is a Reader for the GETAvailablehammers structure.
type GETAvailablehammersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETAvailablehammersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETAvailablehammersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETAvailablehammersOK creates a GETAvailablehammersOK with default headers values
func NewGETAvailablehammersOK() *GETAvailablehammersOK {
	return &GETAvailablehammersOK{}
}

/*GETAvailablehammersOK handles this case with default header values.

GETAvailablehammersOK g e t availablehammers o k
*/
type GETAvailablehammersOK struct {
	Payload *models.AvailablehammersOutput
}

func (o *GETAvailablehammersOK) Error() string {
	return fmt.Sprintf("[GET /availablehammers/{id}][%d] gETAvailablehammersOK  %+v", 200, o.Payload)
}

func (o *GETAvailablehammersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AvailablehammersOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
