package availablehammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETAvailablehammersParams creates a new GETAvailablehammersParams object
// with the default values initialized.
func NewGETAvailablehammersParams() *GETAvailablehammersParams {
	var ()
	return &GETAvailablehammersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETAvailablehammersParamsWithTimeout creates a new GETAvailablehammersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETAvailablehammersParamsWithTimeout(timeout time.Duration) *GETAvailablehammersParams {
	var ()
	return &GETAvailablehammersParams{

		timeout: timeout,
	}
}

// NewGETAvailablehammersParamsWithContext creates a new GETAvailablehammersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETAvailablehammersParamsWithContext(ctx context.Context) *GETAvailablehammersParams {
	var ()
	return &GETAvailablehammersParams{

		Context: ctx,
	}
}

/*GETAvailablehammersParams contains all the parameters to send to the API endpoint
for the g e t availablehammers operation typically these are written to a http.Request
*/
type GETAvailablehammersParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t availablehammers params
func (o *GETAvailablehammersParams) WithTimeout(timeout time.Duration) *GETAvailablehammersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t availablehammers params
func (o *GETAvailablehammersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t availablehammers params
func (o *GETAvailablehammersParams) WithContext(ctx context.Context) *GETAvailablehammersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t availablehammers params
func (o *GETAvailablehammersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t availablehammers params
func (o *GETAvailablehammersParams) WithID(id string) *GETAvailablehammersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t availablehammers params
func (o *GETAvailablehammersParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETAvailablehammersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
