package availablehammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTAvailablehammersParams creates a new LISTAvailablehammersParams object
// with the default values initialized.
func NewLISTAvailablehammersParams() *LISTAvailablehammersParams {

	return &LISTAvailablehammersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTAvailablehammersParamsWithTimeout creates a new LISTAvailablehammersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTAvailablehammersParamsWithTimeout(timeout time.Duration) *LISTAvailablehammersParams {

	return &LISTAvailablehammersParams{

		timeout: timeout,
	}
}

// NewLISTAvailablehammersParamsWithContext creates a new LISTAvailablehammersParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTAvailablehammersParamsWithContext(ctx context.Context) *LISTAvailablehammersParams {

	return &LISTAvailablehammersParams{

		Context: ctx,
	}
}

/*LISTAvailablehammersParams contains all the parameters to send to the API endpoint
for the l i s t availablehammers operation typically these are written to a http.Request
*/
type LISTAvailablehammersParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t availablehammers params
func (o *LISTAvailablehammersParams) WithTimeout(timeout time.Duration) *LISTAvailablehammersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t availablehammers params
func (o *LISTAvailablehammersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t availablehammers params
func (o *LISTAvailablehammersParams) WithContext(ctx context.Context) *LISTAvailablehammersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t availablehammers params
func (o *LISTAvailablehammersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTAvailablehammersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
