package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETECapabilitiesParams creates a new DELETECapabilitiesParams object
// with the default values initialized.
func NewDELETECapabilitiesParams() *DELETECapabilitiesParams {
	var ()
	return &DELETECapabilitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETECapabilitiesParamsWithTimeout creates a new DELETECapabilitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETECapabilitiesParamsWithTimeout(timeout time.Duration) *DELETECapabilitiesParams {
	var ()
	return &DELETECapabilitiesParams{

		timeout: timeout,
	}
}

// NewDELETECapabilitiesParamsWithContext creates a new DELETECapabilitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETECapabilitiesParamsWithContext(ctx context.Context) *DELETECapabilitiesParams {
	var ()
	return &DELETECapabilitiesParams{

		Context: ctx,
	}
}

/*DELETECapabilitiesParams contains all the parameters to send to the API endpoint
for the d e l e t e capabilities operation typically these are written to a http.Request
*/
type DELETECapabilitiesParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) WithTimeout(timeout time.Duration) *DELETECapabilitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) WithContext(ctx context.Context) *DELETECapabilitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) WithID(id string) *DELETECapabilitiesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e capabilities params
func (o *DELETECapabilitiesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETECapabilitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
