package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETECapabilitiesReader is a Reader for the DELETECapabilities structure.
type DELETECapabilitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETECapabilitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETECapabilitiesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETECapabilitiesNoContent creates a DELETECapabilitiesNoContent with default headers values
func NewDELETECapabilitiesNoContent() *DELETECapabilitiesNoContent {
	return &DELETECapabilitiesNoContent{}
}

/*DELETECapabilitiesNoContent handles this case with default header values.

DELETECapabilitiesNoContent d e l e t e capabilities no content
*/
type DELETECapabilitiesNoContent struct {
}

func (o *DELETECapabilitiesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /capabilities/{id}][%d] dELETECapabilitiesNoContent ", 204)
}

func (o *DELETECapabilitiesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
