package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTCapabilitiesParams creates a new LISTCapabilitiesParams object
// with the default values initialized.
func NewLISTCapabilitiesParams() *LISTCapabilitiesParams {

	return &LISTCapabilitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTCapabilitiesParamsWithTimeout creates a new LISTCapabilitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTCapabilitiesParamsWithTimeout(timeout time.Duration) *LISTCapabilitiesParams {

	return &LISTCapabilitiesParams{

		timeout: timeout,
	}
}

// NewLISTCapabilitiesParamsWithContext creates a new LISTCapabilitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTCapabilitiesParamsWithContext(ctx context.Context) *LISTCapabilitiesParams {

	return &LISTCapabilitiesParams{

		Context: ctx,
	}
}

/*LISTCapabilitiesParams contains all the parameters to send to the API endpoint
for the l i s t capabilities operation typically these are written to a http.Request
*/
type LISTCapabilitiesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t capabilities params
func (o *LISTCapabilitiesParams) WithTimeout(timeout time.Duration) *LISTCapabilitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t capabilities params
func (o *LISTCapabilitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t capabilities params
func (o *LISTCapabilitiesParams) WithContext(ctx context.Context) *LISTCapabilitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t capabilities params
func (o *LISTCapabilitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTCapabilitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
