package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// PUTCapabilitiesReader is a Reader for the PUTCapabilities structure.
type PUTCapabilitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PUTCapabilitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPUTCapabilitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPUTCapabilitiesOK creates a PUTCapabilitiesOK with default headers values
func NewPUTCapabilitiesOK() *PUTCapabilitiesOK {
	return &PUTCapabilitiesOK{}
}

/*PUTCapabilitiesOK handles this case with default header values.

PUTCapabilitiesOK p u t capabilities o k
*/
type PUTCapabilitiesOK struct {
	Payload *models.CapabilitiesOutput
}

func (o *PUTCapabilitiesOK) Error() string {
	return fmt.Sprintf("[PUT /capabilities/{id}][%d] pUTCapabilitiesOK  %+v", 200, o.Payload)
}

func (o *PUTCapabilitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CapabilitiesOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
