package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DELETEDeploymentsNoContent d e l e t e deployments no content

swagger:response dELETEDeploymentsNoContent
*/
type DELETEDeploymentsNoContent struct {
}

// NewDELETEDeploymentsNoContent creates DELETEDeploymentsNoContent with default headers values
func NewDELETEDeploymentsNoContent() *DELETEDeploymentsNoContent {
	return &DELETEDeploymentsNoContent{}
}

// WriteResponse to the client
func (o *DELETEDeploymentsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
