package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PUTDeploymentsHandlerFunc turns a function with the right signature into a p u t deployments handler
type PUTDeploymentsHandlerFunc func(PUTDeploymentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PUTDeploymentsHandlerFunc) Handle(params PUTDeploymentsParams) middleware.Responder {
	return fn(params)
}

// PUTDeploymentsHandler interface for that can handle valid p u t deployments params
type PUTDeploymentsHandler interface {
	Handle(PUTDeploymentsParams) middleware.Responder
}

// NewPUTDeployments creates a new http.Handler for the p u t deployments operation
func NewPUTDeployments(ctx *middleware.Context, handler PUTDeploymentsHandler) *PUTDeployments {
	return &PUTDeployments{Context: ctx, Handler: handler}
}

/*PUTDeployments swagger:route PUT /deployments/{id} Deployments pUTDeployments

Update Deployments

*/
type PUTDeployments struct {
	Context *middleware.Context
	Handler PUTDeploymentsHandler
}

func (o *PUTDeployments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPUTDeploymentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
