package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*PUTDeploymentsOK p u t deployments o k

swagger:response pUTDeploymentsOK
*/
type PUTDeploymentsOK struct {

	// In: body
	Payload *models.DeploymentsOutput `json:"body,omitempty"`
}

// NewPUTDeploymentsOK creates PUTDeploymentsOK with default headers values
func NewPUTDeploymentsOK() *PUTDeploymentsOK {
	return &PUTDeploymentsOK{}
}

// WithPayload adds the payload to the p u t deployments o k response
func (o *PUTDeploymentsOK) WithPayload(payload *models.DeploymentsOutput) *PUTDeploymentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p u t deployments o k response
func (o *PUTDeploymentsOK) SetPayload(payload *models.DeploymentsOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PUTDeploymentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
