package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETENetworkrouterReader is a Reader for the DELETENetworkrouter structure.
type DELETENetworkrouterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETENetworkrouterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETENetworkrouterNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETENetworkrouterNoContent creates a DELETENetworkrouterNoContent with default headers values
func NewDELETENetworkrouterNoContent() *DELETENetworkrouterNoContent {
	return &DELETENetworkrouterNoContent{}
}

/*DELETENetworkrouterNoContent handles this case with default header values.

DELETENetworkrouterNoContent d e l e t e networkrouter no content
*/
type DELETENetworkrouterNoContent struct {
}

func (o *DELETENetworkrouterNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networkrouters/{id}][%d] dELETENetworkrouterNoContent ", 204)
}

func (o *DELETENetworkrouterNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
