package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTNetworkrouterParams creates a new POSTNetworkrouterParams object
// with the default values initialized.
func NewPOSTNetworkrouterParams() *POSTNetworkrouterParams {
	var ()
	return &POSTNetworkrouterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTNetworkrouterParamsWithTimeout creates a new POSTNetworkrouterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTNetworkrouterParamsWithTimeout(timeout time.Duration) *POSTNetworkrouterParams {
	var ()
	return &POSTNetworkrouterParams{

		timeout: timeout,
	}
}

// NewPOSTNetworkrouterParamsWithContext creates a new POSTNetworkrouterParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTNetworkrouterParamsWithContext(ctx context.Context) *POSTNetworkrouterParams {
	var ()
	return &POSTNetworkrouterParams{

		Context: ctx,
	}
}

/*POSTNetworkrouterParams contains all the parameters to send to the API endpoint
for the p o s t networkrouter operation typically these are written to a http.Request
*/
type POSTNetworkrouterParams struct {

	/*Body*/
	Body *models.NetworkrouterInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) WithTimeout(timeout time.Duration) *POSTNetworkrouterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) WithContext(ctx context.Context) *POSTNetworkrouterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) WithBody(body *models.NetworkrouterInput) *POSTNetworkrouterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t networkrouter params
func (o *POSTNetworkrouterParams) SetBody(body *models.NetworkrouterInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTNetworkrouterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NetworkrouterInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
