package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTNetworkrouterReader is a Reader for the POSTNetworkrouter structure.
type POSTNetworkrouterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTNetworkrouterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTNetworkrouterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTNetworkrouterCreated creates a POSTNetworkrouterCreated with default headers values
func NewPOSTNetworkrouterCreated() *POSTNetworkrouterCreated {
	return &POSTNetworkrouterCreated{}
}

/*POSTNetworkrouterCreated handles this case with default header values.

POSTNetworkrouterCreated p o s t networkrouter created
*/
type POSTNetworkrouterCreated struct {
	Payload *models.NetworkrouterOutput
}

func (o *POSTNetworkrouterCreated) Error() string {
	return fmt.Sprintf("[POST /networkrouters][%d] pOSTNetworkrouterCreated  %+v", 201, o.Payload)
}

func (o *POSTNetworkrouterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkrouterOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
