package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// PUTNetworkrouterReader is a Reader for the PUTNetworkrouter structure.
type PUTNetworkrouterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PUTNetworkrouterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPUTNetworkrouterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPUTNetworkrouterOK creates a PUTNetworkrouterOK with default headers values
func NewPUTNetworkrouterOK() *PUTNetworkrouterOK {
	return &PUTNetworkrouterOK{}
}

/*PUTNetworkrouterOK handles this case with default header values.

PUTNetworkrouterOK p u t networkrouter o k
*/
type PUTNetworkrouterOK struct {
	Payload *models.NetworkrouterOutput
}

func (o *PUTNetworkrouterOK) Error() string {
	return fmt.Sprintf("[PUT /networkrouters/{id}][%d] pUTNetworkrouterOK  %+v", 200, o.Payload)
}

func (o *PUTNetworkrouterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkrouterOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
