package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTNetworkrouterParams creates a new PUTNetworkrouterParams object
// with the default values initialized.
func NewPUTNetworkrouterParams() *PUTNetworkrouterParams {
	var ()
	return &PUTNetworkrouterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTNetworkrouterParamsWithTimeout creates a new PUTNetworkrouterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTNetworkrouterParamsWithTimeout(timeout time.Duration) *PUTNetworkrouterParams {
	var ()
	return &PUTNetworkrouterParams{

		timeout: timeout,
	}
}

// NewPUTNetworkrouterParamsWithContext creates a new PUTNetworkrouterParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTNetworkrouterParamsWithContext(ctx context.Context) *PUTNetworkrouterParams {
	var ()
	return &PUTNetworkrouterParams{

		Context: ctx,
	}
}

/*PUTNetworkrouterParams contains all the parameters to send to the API endpoint
for the p u t networkrouter operation typically these are written to a http.Request
*/
type PUTNetworkrouterParams struct {

	/*Body*/
	Body *models.NetworkrouterInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t networkrouter params
func (o *PUTNetworkrouterParams) WithTimeout(timeout time.Duration) *PUTNetworkrouterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t networkrouter params
func (o *PUTNetworkrouterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t networkrouter params
func (o *PUTNetworkrouterParams) WithContext(ctx context.Context) *PUTNetworkrouterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t networkrouter params
func (o *PUTNetworkrouterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t networkrouter params
func (o *PUTNetworkrouterParams) WithBody(body *models.NetworkrouterInput) *PUTNetworkrouterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t networkrouter params
func (o *PUTNetworkrouterParams) SetBody(body *models.NetworkrouterInput) {
	o.Body = body
}

// WithID adds the id to the p u t networkrouter params
func (o *PUTNetworkrouterParams) WithID(id string) *PUTNetworkrouterParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t networkrouter params
func (o *PUTNetworkrouterParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTNetworkrouterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NetworkrouterInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
