package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETHammerParams creates a new GETHammerParams object
// with the default values initialized.
func NewGETHammerParams() *GETHammerParams {
	var ()
	return &GETHammerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETHammerParamsWithTimeout creates a new GETHammerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETHammerParamsWithTimeout(timeout time.Duration) *GETHammerParams {
	var ()
	return &GETHammerParams{

		timeout: timeout,
	}
}

// NewGETHammerParamsWithContext creates a new GETHammerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETHammerParamsWithContext(ctx context.Context) *GETHammerParams {
	var ()
	return &GETHammerParams{

		Context: ctx,
	}
}

/*GETHammerParams contains all the parameters to send to the API endpoint
for the g e t hammer operation typically these are written to a http.Request
*/
type GETHammerParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t hammer params
func (o *GETHammerParams) WithTimeout(timeout time.Duration) *GETHammerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t hammer params
func (o *GETHammerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t hammer params
func (o *GETHammerParams) WithContext(ctx context.Context) *GETHammerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t hammer params
func (o *GETHammerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t hammer params
func (o *GETHammerParams) WithID(id string) *GETHammerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t hammer params
func (o *GETHammerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETHammerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
