package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTHammersReader is a Reader for the LISTHammers structure.
type LISTHammersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTHammersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTHammersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTHammersOK creates a LISTHammersOK with default headers values
func NewLISTHammersOK() *LISTHammersOK {
	return &LISTHammersOK{}
}

/*LISTHammersOK handles this case with default header values.

LISTHammersOK l i s t hammers o k
*/
type LISTHammersOK struct {
	Payload []*models.HammerOutput
}

func (o *LISTHammersOK) Error() string {
	return fmt.Sprintf("[GET /hammers][%d] lISTHammersOK  %+v", 200, o.Payload)
}

func (o *LISTHammersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
