package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTHammersParams creates a new LISTHammersParams object
// with the default values initialized.
func NewLISTHammersParams() *LISTHammersParams {

	return &LISTHammersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTHammersParamsWithTimeout creates a new LISTHammersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTHammersParamsWithTimeout(timeout time.Duration) *LISTHammersParams {

	return &LISTHammersParams{

		timeout: timeout,
	}
}

// NewLISTHammersParamsWithContext creates a new LISTHammersParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTHammersParamsWithContext(ctx context.Context) *LISTHammersParams {

	return &LISTHammersParams{

		Context: ctx,
	}
}

/*LISTHammersParams contains all the parameters to send to the API endpoint
for the l i s t hammers operation typically these are written to a http.Request
*/
type LISTHammersParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t hammers params
func (o *LISTHammersParams) WithTimeout(timeout time.Duration) *LISTHammersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t hammers params
func (o *LISTHammersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t hammers params
func (o *LISTHammersParams) WithContext(ctx context.Context) *LISTHammersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t hammers params
func (o *LISTHammersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTHammersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
