package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTHammerParams creates a new PUTHammerParams object
// with the default values initialized.
func NewPUTHammerParams() *PUTHammerParams {
	var ()
	return &PUTHammerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTHammerParamsWithTimeout creates a new PUTHammerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTHammerParamsWithTimeout(timeout time.Duration) *PUTHammerParams {
	var ()
	return &PUTHammerParams{

		timeout: timeout,
	}
}

// NewPUTHammerParamsWithContext creates a new PUTHammerParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTHammerParamsWithContext(ctx context.Context) *PUTHammerParams {
	var ()
	return &PUTHammerParams{

		Context: ctx,
	}
}

/*PUTHammerParams contains all the parameters to send to the API endpoint
for the p u t hammer operation typically these are written to a http.Request
*/
type PUTHammerParams struct {

	/*Body*/
	Body *models.HammerInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t hammer params
func (o *PUTHammerParams) WithTimeout(timeout time.Duration) *PUTHammerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t hammer params
func (o *PUTHammerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t hammer params
func (o *PUTHammerParams) WithContext(ctx context.Context) *PUTHammerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t hammer params
func (o *PUTHammerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t hammer params
func (o *PUTHammerParams) WithBody(body *models.HammerInput) *PUTHammerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t hammer params
func (o *PUTHammerParams) SetBody(body *models.HammerInput) {
	o.Body = body
}

// WithID adds the id to the p u t hammer params
func (o *PUTHammerParams) WithID(id string) *PUTHammerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t hammer params
func (o *PUTHammerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTHammerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.HammerInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
