package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETTenantOK g e t tenant o k

swagger:response gETTenantOK
*/
type GETTenantOK struct {

	// In: body
	Payload *models.TenantOutput `json:"body,omitempty"`
}

// NewGETTenantOK creates GETTenantOK with default headers values
func NewGETTenantOK() *GETTenantOK {
	return &GETTenantOK{}
}

// WithPayload adds the payload to the g e t tenant o k response
func (o *GETTenantOK) WithPayload(payload *models.TenantOutput) *GETTenantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t tenant o k response
func (o *GETTenantOK) SetPayload(payload *models.TenantOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETTenantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
