package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTTenantCreated p o s t tenant created

swagger:response pOSTTenantCreated
*/
type POSTTenantCreated struct {

	// In: body
	Payload *models.TenantOutput `json:"body,omitempty"`
}

// NewPOSTTenantCreated creates POSTTenantCreated with default headers values
func NewPOSTTenantCreated() *POSTTenantCreated {
	return &POSTTenantCreated{}
}

// WithPayload adds the payload to the p o s t tenant created response
func (o *POSTTenantCreated) WithPayload(payload *models.TenantOutput) *POSTTenantCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t tenant created response
func (o *POSTTenantCreated) SetPayload(payload *models.TenantOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTTenantCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
