package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DELETEJigNoContent d e l e t e jig no content

swagger:response dELETEJigNoContent
*/
type DELETEJigNoContent struct {
}

// NewDELETEJigNoContent creates DELETEJigNoContent with default headers values
func NewDELETEJigNoContent() *DELETEJigNoContent {
	return &DELETEJigNoContent{}
}

// WriteResponse to the client
func (o *DELETEJigNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
