package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTJigsOK l i s t jigs o k

swagger:response lISTJigsOK
*/
type LISTJigsOK struct {

	// In: body
	Payload []*models.JigOutput `json:"body,omitempty"`
}

// NewLISTJigsOK creates LISTJigsOK with default headers values
func NewLISTJigsOK() *LISTJigsOK {
	return &LISTJigsOK{}
}

// WithPayload adds the payload to the l i s t jigs o k response
func (o *LISTJigsOK) WithPayload(payload []*models.JigOutput) *LISTJigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t jigs o k response
func (o *LISTJigsOK) SetPayload(payload []*models.JigOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTJigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
