package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// POSTJigHandlerFunc turns a function with the right signature into a p o s t jig handler
type POSTJigHandlerFunc func(POSTJigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn POSTJigHandlerFunc) Handle(params POSTJigParams) middleware.Responder {
	return fn(params)
}

// POSTJigHandler interface for that can handle valid p o s t jig params
type POSTJigHandler interface {
	Handle(POSTJigParams) middleware.Responder
}

// NewPOSTJig creates a new http.Handler for the p o s t jig operation
func NewPOSTJig(ctx *middleware.Context, handler POSTJigHandler) *POSTJig {
	return &POSTJig{Context: ctx, Handler: handler}
}

/*POSTJig swagger:route POST /jigs Jigs pOSTJig

Create Jig

*/
type POSTJig struct {
	Context *middleware.Context
	Handler POSTJigHandler
}

func (o *POSTJig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPOSTJigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
