package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTJigCreated p o s t jig created

swagger:response pOSTJigCreated
*/
type POSTJigCreated struct {

	// In: body
	Payload *models.JigOutput `json:"body,omitempty"`
}

// NewPOSTJigCreated creates POSTJigCreated with default headers values
func NewPOSTJigCreated() *POSTJigCreated {
	return &POSTJigCreated{}
}

// WithPayload adds the payload to the p o s t jig created response
func (o *POSTJigCreated) WithPayload(payload *models.JigOutput) *POSTJigCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t jig created response
func (o *POSTJigCreated) SetPayload(payload *models.JigOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTJigCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
