package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETERolesReader is a Reader for the DELETERoles structure.
type DELETERolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETERolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETERolesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETERolesNoContent creates a DELETERolesNoContent with default headers values
func NewDELETERolesNoContent() *DELETERolesNoContent {
	return &DELETERolesNoContent{}
}

/*DELETERolesNoContent handles this case with default header values.

DELETERolesNoContent d e l e t e roles no content
*/
type DELETERolesNoContent struct {
}

func (o *DELETERolesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /roles/{id}][%d] dELETERolesNoContent ", 204)
}

func (o *DELETERolesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
