package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETRolesReader is a Reader for the GETRoles structure.
type GETRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETRolesOK creates a GETRolesOK with default headers values
func NewGETRolesOK() *GETRolesOK {
	return &GETRolesOK{}
}

/*GETRolesOK handles this case with default header values.

GETRolesOK g e t roles o k
*/
type GETRolesOK struct {
	Payload *models.RolesOutput
}

func (o *GETRolesOK) Error() string {
	return fmt.Sprintf("[GET /roles/{id}][%d] gETRolesOK  %+v", 200, o.Payload)
}

func (o *GETRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RolesOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
