package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTRolesParams creates a new LISTRolesParams object
// with the default values initialized.
func NewLISTRolesParams() *LISTRolesParams {

	return &LISTRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTRolesParamsWithTimeout creates a new LISTRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTRolesParamsWithTimeout(timeout time.Duration) *LISTRolesParams {

	return &LISTRolesParams{

		timeout: timeout,
	}
}

// NewLISTRolesParamsWithContext creates a new LISTRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTRolesParamsWithContext(ctx context.Context) *LISTRolesParams {

	return &LISTRolesParams{

		Context: ctx,
	}
}

/*LISTRolesParams contains all the parameters to send to the API endpoint
for the l i s t roles operation typically these are written to a http.Request
*/
type LISTRolesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t roles params
func (o *LISTRolesParams) WithTimeout(timeout time.Duration) *LISTRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t roles params
func (o *LISTRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t roles params
func (o *LISTRolesParams) WithContext(ctx context.Context) *LISTRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t roles params
func (o *LISTRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
