package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTRolesReader is a Reader for the LISTRoles structure.
type LISTRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTRolesOK creates a LISTRolesOK with default headers values
func NewLISTRolesOK() *LISTRolesOK {
	return &LISTRolesOK{}
}

/*LISTRolesOK handles this case with default header values.

LISTRolesOK l i s t roles o k
*/
type LISTRolesOK struct {
	Payload []*models.RolesOutput
}

func (o *LISTRolesOK) Error() string {
	return fmt.Sprintf("[GET /roles][%d] lISTRolesOK  %+v", 200, o.Payload)
}

func (o *LISTRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
