package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEJigReader is a Reader for the DELETEJig structure.
type DELETEJigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEJigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEJigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEJigNoContent creates a DELETEJigNoContent with default headers values
func NewDELETEJigNoContent() *DELETEJigNoContent {
	return &DELETEJigNoContent{}
}

/*DELETEJigNoContent handles this case with default header values.

DELETEJigNoContent d e l e t e jig no content
*/
type DELETEJigNoContent struct {
}

func (o *DELETEJigNoContent) Error() string {
	return fmt.Sprintf("[DELETE /jigs/{id}][%d] dELETEJigNoContent ", 204)
}

func (o *DELETEJigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
