package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETJigParams creates a new GETJigParams object
// with the default values initialized.
func NewGETJigParams() *GETJigParams {
	var ()
	return &GETJigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETJigParamsWithTimeout creates a new GETJigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETJigParamsWithTimeout(timeout time.Duration) *GETJigParams {
	var ()
	return &GETJigParams{

		timeout: timeout,
	}
}

// NewGETJigParamsWithContext creates a new GETJigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETJigParamsWithContext(ctx context.Context) *GETJigParams {
	var ()
	return &GETJigParams{

		Context: ctx,
	}
}

/*GETJigParams contains all the parameters to send to the API endpoint
for the g e t jig operation typically these are written to a http.Request
*/
type GETJigParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t jig params
func (o *GETJigParams) WithTimeout(timeout time.Duration) *GETJigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t jig params
func (o *GETJigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t jig params
func (o *GETJigParams) WithContext(ctx context.Context) *GETJigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t jig params
func (o *GETJigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t jig params
func (o *GETJigParams) WithID(id string) *GETJigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t jig params
func (o *GETJigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETJigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
