package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTJigsParams creates a new LISTJigsParams object
// with the default values initialized.
func NewLISTJigsParams() *LISTJigsParams {

	return &LISTJigsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTJigsParamsWithTimeout creates a new LISTJigsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTJigsParamsWithTimeout(timeout time.Duration) *LISTJigsParams {

	return &LISTJigsParams{

		timeout: timeout,
	}
}

// NewLISTJigsParamsWithContext creates a new LISTJigsParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTJigsParamsWithContext(ctx context.Context) *LISTJigsParams {

	return &LISTJigsParams{

		Context: ctx,
	}
}

/*LISTJigsParams contains all the parameters to send to the API endpoint
for the l i s t jigs operation typically these are written to a http.Request
*/
type LISTJigsParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t jigs params
func (o *LISTJigsParams) WithTimeout(timeout time.Duration) *LISTJigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t jigs params
func (o *LISTJigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t jigs params
func (o *LISTJigsParams) WithContext(ctx context.Context) *LISTJigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t jigs params
func (o *LISTJigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTJigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
