package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTJigReader is a Reader for the POSTJig structure.
type POSTJigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTJigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTJigCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTJigCreated creates a POSTJigCreated with default headers values
func NewPOSTJigCreated() *POSTJigCreated {
	return &POSTJigCreated{}
}

/*POSTJigCreated handles this case with default header values.

POSTJigCreated p o s t jig created
*/
type POSTJigCreated struct {
	Payload *models.JigOutput
}

func (o *POSTJigCreated) Error() string {
	return fmt.Sprintf("[POST /jigs][%d] pOSTJigCreated  %+v", 201, o.Payload)
}

func (o *POSTJigCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JigOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
