package jigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// PUTJigReader is a Reader for the PUTJig structure.
type PUTJigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PUTJigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPUTJigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPUTJigOK creates a PUTJigOK with default headers values
func NewPUTJigOK() *PUTJigOK {
	return &PUTJigOK{}
}

/*PUTJigOK handles this case with default header values.

PUTJigOK p u t jig o k
*/
type PUTJigOK struct {
	Payload *models.JigOutput
}

func (o *PUTJigOK) Error() string {
	return fmt.Sprintf("[PUT /jigs/{id}][%d] pUTJigOK  %+v", 200, o.Payload)
}

func (o *PUTJigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JigOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
