package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETTenantReader is a Reader for the GETTenant structure.
type GETTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETTenantOK creates a GETTenantOK with default headers values
func NewGETTenantOK() *GETTenantOK {
	return &GETTenantOK{}
}

/*GETTenantOK handles this case with default header values.

GETTenantOK g e t tenant o k
*/
type GETTenantOK struct {
	Payload *models.TenantOutput
}

func (o *GETTenantOK) Error() string {
	return fmt.Sprintf("[GET /tenants/{id}][%d] gETTenantOK  %+v", 200, o.Payload)
}

func (o *GETTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
