package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTTenantsReader is a Reader for the LISTTenants structure.
type LISTTenantsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTTenantsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTTenantsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTTenantsOK creates a LISTTenantsOK with default headers values
func NewLISTTenantsOK() *LISTTenantsOK {
	return &LISTTenantsOK{}
}

/*LISTTenantsOK handles this case with default header values.

LISTTenantsOK l i s t tenants o k
*/
type LISTTenantsOK struct {
	Payload []*models.TenantOutput
}

func (o *LISTTenantsOK) Error() string {
	return fmt.Sprintf("[GET /tenants][%d] lISTTenantsOK  %+v", 200, o.Payload)
}

func (o *LISTTenantsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
