package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTTenantParams creates a new POSTTenantParams object
// with the default values initialized.
func NewPOSTTenantParams() *POSTTenantParams {
	var ()
	return &POSTTenantParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTTenantParamsWithTimeout creates a new POSTTenantParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTTenantParamsWithTimeout(timeout time.Duration) *POSTTenantParams {
	var ()
	return &POSTTenantParams{

		timeout: timeout,
	}
}

// NewPOSTTenantParamsWithContext creates a new POSTTenantParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTTenantParamsWithContext(ctx context.Context) *POSTTenantParams {
	var ()
	return &POSTTenantParams{

		Context: ctx,
	}
}

/*POSTTenantParams contains all the parameters to send to the API endpoint
for the p o s t tenant operation typically these are written to a http.Request
*/
type POSTTenantParams struct {

	/*Body*/
	Body *models.TenantInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t tenant params
func (o *POSTTenantParams) WithTimeout(timeout time.Duration) *POSTTenantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t tenant params
func (o *POSTTenantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t tenant params
func (o *POSTTenantParams) WithContext(ctx context.Context) *POSTTenantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t tenant params
func (o *POSTTenantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t tenant params
func (o *POSTTenantParams) WithBody(body *models.TenantInput) *POSTTenantParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t tenant params
func (o *POSTTenantParams) SetBody(body *models.TenantInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTTenantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.TenantInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
