package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTTenantReader is a Reader for the POSTTenant structure.
type POSTTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTTenantCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTTenantCreated creates a POSTTenantCreated with default headers values
func NewPOSTTenantCreated() *POSTTenantCreated {
	return &POSTTenantCreated{}
}

/*POSTTenantCreated handles this case with default header values.

POSTTenantCreated p o s t tenant created
*/
type POSTTenantCreated struct {
	Payload *models.TenantOutput
}

func (o *POSTTenantCreated) Error() string {
	return fmt.Sprintf("[POST /tenants][%d] pOSTTenantCreated  %+v", 201, o.Payload)
}

func (o *POSTTenantCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
