package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETNodeOK g e t node o k

swagger:response gETNodeOK
*/
type GETNodeOK struct {

	// In: body
	Payload *models.NodeOutput `json:"body,omitempty"`
}

// NewGETNodeOK creates GETNodeOK with default headers values
func NewGETNodeOK() *GETNodeOK {
	return &GETNodeOK{}
}

// WithPayload adds the payload to the g e t node o k response
func (o *GETNodeOK) WithPayload(payload *models.NodeOutput) *GETNodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t node o k response
func (o *GETNodeOK) SetPayload(payload *models.NodeOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETNodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
