package barclamps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTBarclampsOK l i s t barclamps o k

swagger:response lISTBarclampsOK
*/
type LISTBarclampsOK struct {

	// In: body
	Payload []*models.BarclampOutput `json:"body,omitempty"`
}

// NewLISTBarclampsOK creates LISTBarclampsOK with default headers values
func NewLISTBarclampsOK() *LISTBarclampsOK {
	return &LISTBarclampsOK{}
}

// WithPayload adds the payload to the l i s t barclamps o k response
func (o *LISTBarclampsOK) WithPayload(payload []*models.BarclampOutput) *LISTBarclampsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t barclamps o k response
func (o *LISTBarclampsOK) SetPayload(payload []*models.BarclampOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTBarclampsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
