package barclamps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTBarclampCreated p o s t barclamp created

swagger:response pOSTBarclampCreated
*/
type POSTBarclampCreated struct {

	// In: body
	Payload *models.BarclampOutput `json:"body,omitempty"`
}

// NewPOSTBarclampCreated creates POSTBarclampCreated with default headers values
func NewPOSTBarclampCreated() *POSTBarclampCreated {
	return &POSTBarclampCreated{}
}

// WithPayload adds the payload to the p o s t barclamp created response
func (o *POSTBarclampCreated) WithPayload(payload *models.BarclampOutput) *POSTBarclampCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t barclamp created response
func (o *POSTBarclampCreated) SetPayload(payload *models.BarclampOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTBarclampCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
