package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTNetworksOK l i s t networks o k

swagger:response lISTNetworksOK
*/
type LISTNetworksOK struct {

	// In: body
	Payload []*models.NetworkOutput `json:"body,omitempty"`
}

// NewLISTNetworksOK creates LISTNetworksOK with default headers values
func NewLISTNetworksOK() *LISTNetworksOK {
	return &LISTNetworksOK{}
}

// WithPayload adds the payload to the l i s t networks o k response
func (o *LISTNetworksOK) WithPayload(payload []*models.NetworkOutput) *LISTNetworksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t networks o k response
func (o *LISTNetworksOK) SetPayload(payload []*models.NetworkOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTNetworksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
