package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LISTNetworksHandlerFunc turns a function with the right signature into a l i s t networks handler
type LISTNetworksHandlerFunc func(LISTNetworksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LISTNetworksHandlerFunc) Handle(params LISTNetworksParams) middleware.Responder {
	return fn(params)
}

// LISTNetworksHandler interface for that can handle valid l i s t networks params
type LISTNetworksHandler interface {
	Handle(LISTNetworksParams) middleware.Responder
}

// NewLISTNetworks creates a new http.Handler for the l i s t networks operation
func NewLISTNetworks(ctx *middleware.Context, handler LISTNetworksHandler) *LISTNetworks {
	return &LISTNetworks{Context: ctx, Handler: handler}
}

/*LISTNetworks swagger:route GET /networks Networks lISTNetworks

List Networks

*/
type LISTNetworks struct {
	Context *middleware.Context
	Handler LISTNetworksHandler
}

func (o *LISTNetworks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewLISTNetworksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
