package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTNetworkCreated p o s t network created

swagger:response pOSTNetworkCreated
*/
type POSTNetworkCreated struct {

	// In: body
	Payload *models.NetworkOutput `json:"body,omitempty"`
}

// NewPOSTNetworkCreated creates POSTNetworkCreated with default headers values
func NewPOSTNetworkCreated() *POSTNetworkCreated {
	return &POSTNetworkCreated{}
}

// WithPayload adds the payload to the p o s t network created response
func (o *POSTNetworkCreated) WithPayload(payload *models.NetworkOutput) *POSTNetworkCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t network created response
func (o *POSTNetworkCreated) SetPayload(payload *models.NetworkOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTNetworkCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
