package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEProviderReader is a Reader for the DELETEProvider structure.
type DELETEProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEProviderNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEProviderNoContent creates a DELETEProviderNoContent with default headers values
func NewDELETEProviderNoContent() *DELETEProviderNoContent {
	return &DELETEProviderNoContent{}
}

/*DELETEProviderNoContent handles this case with default header values.

DELETEProviderNoContent d e l e t e provider no content
*/
type DELETEProviderNoContent struct {
}

func (o *DELETEProviderNoContent) Error() string {
	return fmt.Sprintf("[DELETE /providers/{id}][%d] dELETEProviderNoContent ", 204)
}

func (o *DELETEProviderNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
