package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTProviderReader is a Reader for the POSTProvider structure.
type POSTProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTProviderCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTProviderCreated creates a POSTProviderCreated with default headers values
func NewPOSTProviderCreated() *POSTProviderCreated {
	return &POSTProviderCreated{}
}

/*POSTProviderCreated handles this case with default header values.

POSTProviderCreated p o s t provider created
*/
type POSTProviderCreated struct {
	Payload *models.ProviderOutput
}

func (o *POSTProviderCreated) Error() string {
	return fmt.Sprintf("[POST /providers][%d] pOSTProviderCreated  %+v", 201, o.Payload)
}

func (o *POSTProviderCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProviderOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
