package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTProviderParams creates a new POSTProviderParams object
// with the default values initialized.
func NewPOSTProviderParams() *POSTProviderParams {
	var ()
	return &POSTProviderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTProviderParamsWithTimeout creates a new POSTProviderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTProviderParamsWithTimeout(timeout time.Duration) *POSTProviderParams {
	var ()
	return &POSTProviderParams{

		timeout: timeout,
	}
}

// NewPOSTProviderParamsWithContext creates a new POSTProviderParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTProviderParamsWithContext(ctx context.Context) *POSTProviderParams {
	var ()
	return &POSTProviderParams{

		Context: ctx,
	}
}

/*POSTProviderParams contains all the parameters to send to the API endpoint
for the p o s t provider operation typically these are written to a http.Request
*/
type POSTProviderParams struct {

	/*Body*/
	Body *models.ProviderInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t provider params
func (o *POSTProviderParams) WithTimeout(timeout time.Duration) *POSTProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t provider params
func (o *POSTProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t provider params
func (o *POSTProviderParams) WithContext(ctx context.Context) *POSTProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t provider params
func (o *POSTProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t provider params
func (o *POSTProviderParams) WithBody(body *models.ProviderInput) *POSTProviderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t provider params
func (o *POSTProviderParams) SetBody(body *models.ProviderInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.ProviderInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
