package attribs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEAttribReader is a Reader for the DELETEAttrib structure.
type DELETEAttribReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEAttribReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEAttribNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEAttribNoContent creates a DELETEAttribNoContent with default headers values
func NewDELETEAttribNoContent() *DELETEAttribNoContent {
	return &DELETEAttribNoContent{}
}

/*DELETEAttribNoContent handles this case with default header values.

DELETEAttribNoContent d e l e t e attrib no content
*/
type DELETEAttribNoContent struct {
}

func (o *DELETEAttribNoContent) Error() string {
	return fmt.Sprintf("[DELETE /attribs/{id}][%d] dELETEAttribNoContent ", 204)
}

func (o *DELETEAttribNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
