package attribs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTAttribParams creates a new POSTAttribParams object
// with the default values initialized.
func NewPOSTAttribParams() *POSTAttribParams {
	var ()
	return &POSTAttribParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTAttribParamsWithTimeout creates a new POSTAttribParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTAttribParamsWithTimeout(timeout time.Duration) *POSTAttribParams {
	var ()
	return &POSTAttribParams{

		timeout: timeout,
	}
}

// NewPOSTAttribParamsWithContext creates a new POSTAttribParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTAttribParamsWithContext(ctx context.Context) *POSTAttribParams {
	var ()
	return &POSTAttribParams{

		Context: ctx,
	}
}

/*POSTAttribParams contains all the parameters to send to the API endpoint
for the p o s t attrib operation typically these are written to a http.Request
*/
type POSTAttribParams struct {

	/*Body*/
	Body *models.AttribInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t attrib params
func (o *POSTAttribParams) WithTimeout(timeout time.Duration) *POSTAttribParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t attrib params
func (o *POSTAttribParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t attrib params
func (o *POSTAttribParams) WithContext(ctx context.Context) *POSTAttribParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t attrib params
func (o *POSTAttribParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t attrib params
func (o *POSTAttribParams) WithBody(body *models.AttribInput) *POSTAttribParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t attrib params
func (o *POSTAttribParams) SetBody(body *models.AttribInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTAttribParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.AttribInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
