package attribs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTAttribParams creates a new PUTAttribParams object
// with the default values initialized.
func NewPUTAttribParams() *PUTAttribParams {
	var ()
	return &PUTAttribParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTAttribParamsWithTimeout creates a new PUTAttribParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTAttribParamsWithTimeout(timeout time.Duration) *PUTAttribParams {
	var ()
	return &PUTAttribParams{

		timeout: timeout,
	}
}

// NewPUTAttribParamsWithContext creates a new PUTAttribParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTAttribParamsWithContext(ctx context.Context) *PUTAttribParams {
	var ()
	return &PUTAttribParams{

		Context: ctx,
	}
}

/*PUTAttribParams contains all the parameters to send to the API endpoint
for the p u t attrib operation typically these are written to a http.Request
*/
type PUTAttribParams struct {

	/*Body*/
	Body *models.AttribInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t attrib params
func (o *PUTAttribParams) WithTimeout(timeout time.Duration) *PUTAttribParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t attrib params
func (o *PUTAttribParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t attrib params
func (o *PUTAttribParams) WithContext(ctx context.Context) *PUTAttribParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t attrib params
func (o *PUTAttribParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t attrib params
func (o *PUTAttribParams) WithBody(body *models.AttribInput) *PUTAttribParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t attrib params
func (o *PUTAttribParams) SetBody(body *models.AttribInput) {
	o.Body = body
}

// WithID adds the id to the p u t attrib params
func (o *PUTAttribParams) WithID(id string) *PUTAttribParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t attrib params
func (o *PUTAttribParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTAttribParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.AttribInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
