package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETNetworkParams creates a new GETNetworkParams object
// with the default values initialized.
func NewGETNetworkParams() *GETNetworkParams {
	var ()
	return &GETNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETNetworkParamsWithTimeout creates a new GETNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETNetworkParamsWithTimeout(timeout time.Duration) *GETNetworkParams {
	var ()
	return &GETNetworkParams{

		timeout: timeout,
	}
}

// NewGETNetworkParamsWithContext creates a new GETNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETNetworkParamsWithContext(ctx context.Context) *GETNetworkParams {
	var ()
	return &GETNetworkParams{

		Context: ctx,
	}
}

/*GETNetworkParams contains all the parameters to send to the API endpoint
for the g e t network operation typically these are written to a http.Request
*/
type GETNetworkParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t network params
func (o *GETNetworkParams) WithTimeout(timeout time.Duration) *GETNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t network params
func (o *GETNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t network params
func (o *GETNetworkParams) WithContext(ctx context.Context) *GETNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t network params
func (o *GETNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t network params
func (o *GETNetworkParams) WithID(id string) *GETNetworkParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t network params
func (o *GETNetworkParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
