package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTNetworkReader is a Reader for the POSTNetwork structure.
type POSTNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTNetworkCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTNetworkCreated creates a POSTNetworkCreated with default headers values
func NewPOSTNetworkCreated() *POSTNetworkCreated {
	return &POSTNetworkCreated{}
}

/*POSTNetworkCreated handles this case with default header values.

POSTNetworkCreated p o s t network created
*/
type POSTNetworkCreated struct {
	Payload *models.NetworkOutput
}

func (o *POSTNetworkCreated) Error() string {
	return fmt.Sprintf("[POST /networks][%d] pOSTNetworkCreated  %+v", 201, o.Payload)
}

func (o *POSTNetworkCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
