consul:
  extends:
    file: docker-compose-common.yml
    service: consul
  command: agent -config-dir=/etc/consul.d -data-dir=/tmp/consul -server -bootstrap

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres

logging:
  extends:
    file: docker-compose-common.yml
    service: logging

rebar_api:
  extends:
    file: docker-compose-common.yml
    service: rebar_api

rule-engine:
  extends:
    file: docker-compose-common.yml
    service: rule-engine

cloudwrap:
  extends:
    file: docker-compose-common.yml
    service: cloudwrap
