package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETENetworkallocationParams creates a new DELETENetworkallocationParams object
// with the default values initialized.
func NewDELETENetworkallocationParams() *DELETENetworkallocationParams {
	var ()
	return &DELETENetworkallocationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETENetworkallocationParamsWithTimeout creates a new DELETENetworkallocationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETENetworkallocationParamsWithTimeout(timeout time.Duration) *DELETENetworkallocationParams {
	var ()
	return &DELETENetworkallocationParams{

		timeout: timeout,
	}
}

// NewDELETENetworkallocationParamsWithContext creates a new DELETENetworkallocationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETENetworkallocationParamsWithContext(ctx context.Context) *DELETENetworkallocationParams {
	var ()
	return &DELETENetworkallocationParams{

		Context: ctx,
	}
}

/*DELETENetworkallocationParams contains all the parameters to send to the API endpoint
for the d e l e t e networkallocation operation typically these are written to a http.Request
*/
type DELETENetworkallocationParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) WithTimeout(timeout time.Duration) *DELETENetworkallocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) WithContext(ctx context.Context) *DELETENetworkallocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) WithID(id string) *DELETENetworkallocationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e networkallocation params
func (o *DELETENetworkallocationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETENetworkallocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
