package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETENetworkallocationReader is a Reader for the DELETENetworkallocation structure.
type DELETENetworkallocationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETENetworkallocationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETENetworkallocationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETENetworkallocationNoContent creates a DELETENetworkallocationNoContent with default headers values
func NewDELETENetworkallocationNoContent() *DELETENetworkallocationNoContent {
	return &DELETENetworkallocationNoContent{}
}

/*DELETENetworkallocationNoContent handles this case with default header values.

DELETENetworkallocationNoContent d e l e t e networkallocation no content
*/
type DELETENetworkallocationNoContent struct {
}

func (o *DELETENetworkallocationNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networkallocations/{id}][%d] dELETENetworkallocationNoContent ", 204)
}

func (o *DELETENetworkallocationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
