package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETNetworkallocationParams creates a new GETNetworkallocationParams object
// with the default values initialized.
func NewGETNetworkallocationParams() *GETNetworkallocationParams {
	var ()
	return &GETNetworkallocationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETNetworkallocationParamsWithTimeout creates a new GETNetworkallocationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETNetworkallocationParamsWithTimeout(timeout time.Duration) *GETNetworkallocationParams {
	var ()
	return &GETNetworkallocationParams{

		timeout: timeout,
	}
}

// NewGETNetworkallocationParamsWithContext creates a new GETNetworkallocationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETNetworkallocationParamsWithContext(ctx context.Context) *GETNetworkallocationParams {
	var ()
	return &GETNetworkallocationParams{

		Context: ctx,
	}
}

/*GETNetworkallocationParams contains all the parameters to send to the API endpoint
for the g e t networkallocation operation typically these are written to a http.Request
*/
type GETNetworkallocationParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t networkallocation params
func (o *GETNetworkallocationParams) WithTimeout(timeout time.Duration) *GETNetworkallocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t networkallocation params
func (o *GETNetworkallocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t networkallocation params
func (o *GETNetworkallocationParams) WithContext(ctx context.Context) *GETNetworkallocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t networkallocation params
func (o *GETNetworkallocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t networkallocation params
func (o *GETNetworkallocationParams) WithID(id string) *GETNetworkallocationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t networkallocation params
func (o *GETNetworkallocationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETNetworkallocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
