package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTNetworkallocationParams creates a new PUTNetworkallocationParams object
// with the default values initialized.
func NewPUTNetworkallocationParams() *PUTNetworkallocationParams {
	var ()
	return &PUTNetworkallocationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTNetworkallocationParamsWithTimeout creates a new PUTNetworkallocationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTNetworkallocationParamsWithTimeout(timeout time.Duration) *PUTNetworkallocationParams {
	var ()
	return &PUTNetworkallocationParams{

		timeout: timeout,
	}
}

// NewPUTNetworkallocationParamsWithContext creates a new PUTNetworkallocationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTNetworkallocationParamsWithContext(ctx context.Context) *PUTNetworkallocationParams {
	var ()
	return &PUTNetworkallocationParams{

		Context: ctx,
	}
}

/*PUTNetworkallocationParams contains all the parameters to send to the API endpoint
for the p u t networkallocation operation typically these are written to a http.Request
*/
type PUTNetworkallocationParams struct {

	/*Body*/
	Body *models.NetworkallocationInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t networkallocation params
func (o *PUTNetworkallocationParams) WithTimeout(timeout time.Duration) *PUTNetworkallocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t networkallocation params
func (o *PUTNetworkallocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t networkallocation params
func (o *PUTNetworkallocationParams) WithContext(ctx context.Context) *PUTNetworkallocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t networkallocation params
func (o *PUTNetworkallocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t networkallocation params
func (o *PUTNetworkallocationParams) WithBody(body *models.NetworkallocationInput) *PUTNetworkallocationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t networkallocation params
func (o *PUTNetworkallocationParams) SetBody(body *models.NetworkallocationInput) {
	o.Body = body
}

// WithID adds the id to the p u t networkallocation params
func (o *PUTNetworkallocationParams) WithID(id string) *PUTNetworkallocationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t networkallocation params
func (o *PUTNetworkallocationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTNetworkallocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NetworkallocationInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
