package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETProviderOK g e t provider o k

swagger:response gETProviderOK
*/
type GETProviderOK struct {

	// In: body
	Payload *models.ProviderOutput `json:"body,omitempty"`
}

// NewGETProviderOK creates GETProviderOK with default headers values
func NewGETProviderOK() *GETProviderOK {
	return &GETProviderOK{}
}

// WithPayload adds the payload to the g e t provider o k response
func (o *GETProviderOK) WithPayload(payload *models.ProviderOutput) *GETProviderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t provider o k response
func (o *GETProviderOK) SetPayload(payload *models.ProviderOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETProviderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
