package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTProviderCreated p o s t provider created

swagger:response pOSTProviderCreated
*/
type POSTProviderCreated struct {

	// In: body
	Payload *models.ProviderOutput `json:"body,omitempty"`
}

// NewPOSTProviderCreated creates POSTProviderCreated with default headers values
func NewPOSTProviderCreated() *POSTProviderCreated {
	return &POSTProviderCreated{}
}

// WithPayload adds the payload to the p o s t provider created response
func (o *POSTProviderCreated) WithPayload(payload *models.ProviderOutput) *POSTProviderCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t provider created response
func (o *POSTProviderCreated) SetPayload(payload *models.ProviderOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTProviderCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
