package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*PUTProviderOK p u t provider o k

swagger:response pUTProviderOK
*/
type PUTProviderOK struct {

	// In: body
	Payload *models.ProviderOutput `json:"body,omitempty"`
}

// NewPUTProviderOK creates PUTProviderOK with default headers values
func NewPUTProviderOK() *PUTProviderOK {
	return &PUTProviderOK{}
}

// WithPayload adds the payload to the p u t provider o k response
func (o *PUTProviderOK) WithPayload(payload *models.ProviderOutput) *PUTProviderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p u t provider o k response
func (o *PUTProviderOK) SetPayload(payload *models.ProviderOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PUTProviderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
