package availablehammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DELETEAvailablehammersNoContent d e l e t e availablehammers no content

swagger:response dELETEAvailablehammersNoContent
*/
type DELETEAvailablehammersNoContent struct {
}

// NewDELETEAvailablehammersNoContent creates DELETEAvailablehammersNoContent with default headers values
func NewDELETEAvailablehammersNoContent() *DELETEAvailablehammersNoContent {
	return &DELETEAvailablehammersNoContent{}
}

// WriteResponse to the client
func (o *DELETEAvailablehammersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
