package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETRolesOK g e t roles o k

swagger:response gETRolesOK
*/
type GETRolesOK struct {

	// In: body
	Payload *models.RolesOutput `json:"body,omitempty"`
}

// NewGETRolesOK creates GETRolesOK with default headers values
func NewGETRolesOK() *GETRolesOK {
	return &GETRolesOK{}
}

// WithPayload adds the payload to the g e t roles o k response
func (o *GETRolesOK) WithPayload(payload *models.RolesOutput) *GETRolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t roles o k response
func (o *GETRolesOK) SetPayload(payload *models.RolesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETRolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
