package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTRolesCreated p o s t roles created

swagger:response pOSTRolesCreated
*/
type POSTRolesCreated struct {

	// In: body
	Payload *models.RolesOutput `json:"body,omitempty"`
}

// NewPOSTRolesCreated creates POSTRolesCreated with default headers values
func NewPOSTRolesCreated() *POSTRolesCreated {
	return &POSTRolesCreated{}
}

// WithPayload adds the payload to the p o s t roles created response
func (o *POSTRolesCreated) WithPayload(payload *models.RolesOutput) *POSTRolesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t roles created response
func (o *POSTRolesCreated) SetPayload(payload *models.RolesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTRolesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
