package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GETProfileOK g e t profile o k

swagger:response gETProfileOK
*/
type GETProfileOK struct {
}

// NewGETProfileOK creates GETProfileOK with default headers values
func NewGETProfileOK() *GETProfileOK {
	return &GETProfileOK{}
}

// WriteResponse to the client
func (o *GETProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*GETProfileForbidden g e t profile forbidden

swagger:response gETProfileForbidden
*/
type GETProfileForbidden struct {
}

// NewGETProfileForbidden creates GETProfileForbidden with default headers values
func NewGETProfileForbidden() *GETProfileForbidden {
	return &GETProfileForbidden{}
}

// WriteResponse to the client
func (o *GETProfileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

/*GETProfileNotFound g e t profile not found

swagger:response gETProfileNotFound
*/
type GETProfileNotFound struct {
}

// NewGETProfileNotFound creates GETProfileNotFound with default headers values
func NewGETProfileNotFound() *GETProfileNotFound {
	return &GETProfileNotFound{}
}

// WriteResponse to the client
func (o *GETProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
