package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// POSTProfileHandlerFunc turns a function with the right signature into a p o s t profile handler
type POSTProfileHandlerFunc func(POSTProfileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn POSTProfileHandlerFunc) Handle(params POSTProfileParams) middleware.Responder {
	return fn(params)
}

// POSTProfileHandler interface for that can handle valid p o s t profile params
type POSTProfileHandler interface {
	Handle(POSTProfileParams) middleware.Responder
}

// NewPOSTProfile creates a new http.Handler for the p o s t profile operation
func NewPOSTProfile(ctx *middleware.Context, handler POSTProfileHandler) *POSTProfile {
	return &POSTProfile{Context: ctx, Handler: handler}
}

/*POSTProfile swagger:route POST /profiles Profiles pOSTProfile

Create Profile

*/
type POSTProfile struct {
	Context *middleware.Context
	Handler POSTProfileHandler
}

func (o *POSTProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPOSTProfileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
