package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DELETEUsertenantcapabilityHandlerFunc turns a function with the right signature into a d e l e t e usertenantcapability handler
type DELETEUsertenantcapabilityHandlerFunc func(DELETEUsertenantcapabilityParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DELETEUsertenantcapabilityHandlerFunc) Handle(params DELETEUsertenantcapabilityParams) middleware.Responder {
	return fn(params)
}

// DELETEUsertenantcapabilityHandler interface for that can handle valid d e l e t e usertenantcapability params
type DELETEUsertenantcapabilityHandler interface {
	Handle(DELETEUsertenantcapabilityParams) middleware.Responder
}

// NewDELETEUsertenantcapability creates a new http.Handler for the d e l e t e usertenantcapability operation
func NewDELETEUsertenantcapability(ctx *middleware.Context, handler DELETEUsertenantcapabilityHandler) *DELETEUsertenantcapability {
	return &DELETEUsertenantcapability{Context: ctx, Handler: handler}
}

/*DELETEUsertenantcapability swagger:route DELETE /usertenantcapabilities/{id} Usertenantcapabilities dELETEUsertenantcapability

Delete UserTenantCapability

*/
type DELETEUsertenantcapability struct {
	Context *middleware.Context
	Handler DELETEUsertenantcapabilityHandler
}

func (o *DELETEUsertenantcapability) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDELETEUsertenantcapabilityParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
