package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GETUsertenantcapabilityHandlerFunc turns a function with the right signature into a g e t usertenantcapability handler
type GETUsertenantcapabilityHandlerFunc func(GETUsertenantcapabilityParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GETUsertenantcapabilityHandlerFunc) Handle(params GETUsertenantcapabilityParams) middleware.Responder {
	return fn(params)
}

// GETUsertenantcapabilityHandler interface for that can handle valid g e t usertenantcapability params
type GETUsertenantcapabilityHandler interface {
	Handle(GETUsertenantcapabilityParams) middleware.Responder
}

// NewGETUsertenantcapability creates a new http.Handler for the g e t usertenantcapability operation
func NewGETUsertenantcapability(ctx *middleware.Context, handler GETUsertenantcapabilityHandler) *GETUsertenantcapability {
	return &GETUsertenantcapability{Context: ctx, Handler: handler}
}

/*GETUsertenantcapability swagger:route GET /usertenantcapabilities/{id} Usertenantcapabilities gETUsertenantcapability

Get UserTenantCapability

*/
type GETUsertenantcapability struct {
	Context *middleware.Context
	Handler GETUsertenantcapabilityHandler
}

func (o *GETUsertenantcapability) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGETUsertenantcapabilityParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
