package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETUsertenantcapabilityOK g e t usertenantcapability o k

swagger:response gETUsertenantcapabilityOK
*/
type GETUsertenantcapabilityOK struct {

	// In: body
	Payload *models.UsertenantcapabilityOutput `json:"body,omitempty"`
}

// NewGETUsertenantcapabilityOK creates GETUsertenantcapabilityOK with default headers values
func NewGETUsertenantcapabilityOK() *GETUsertenantcapabilityOK {
	return &GETUsertenantcapabilityOK{}
}

// WithPayload adds the payload to the g e t usertenantcapability o k response
func (o *GETUsertenantcapabilityOK) WithPayload(payload *models.UsertenantcapabilityOutput) *GETUsertenantcapabilityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t usertenantcapability o k response
func (o *GETUsertenantcapabilityOK) SetPayload(payload *models.UsertenantcapabilityOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETUsertenantcapabilityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
