package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DELETENetworkrangeNoContent d e l e t e networkrange no content

swagger:response dELETENetworkrangeNoContent
*/
type DELETENetworkrangeNoContent struct {
}

// NewDELETENetworkrangeNoContent creates DELETENetworkrangeNoContent with default headers values
func NewDELETENetworkrangeNoContent() *DELETENetworkrangeNoContent {
	return &DELETENetworkrangeNoContent{}
}

// WriteResponse to the client
func (o *DELETENetworkrangeNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
