package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTNetworkrangesOK l i s t networkranges o k

swagger:response lISTNetworkrangesOK
*/
type LISTNetworkrangesOK struct {

	// In: body
	Payload []*models.NetworkrangeOutput `json:"body,omitempty"`
}

// NewLISTNetworkrangesOK creates LISTNetworkrangesOK with default headers values
func NewLISTNetworkrangesOK() *LISTNetworkrangesOK {
	return &LISTNetworkrangesOK{}
}

// WithPayload adds the payload to the l i s t networkranges o k response
func (o *LISTNetworkrangesOK) WithPayload(payload []*models.NetworkrangeOutput) *LISTNetworkrangesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t networkranges o k response
func (o *LISTNetworkrangesOK) SetPayload(payload []*models.NetworkrangeOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTNetworkrangesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
