package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LISTNetworkrangesHandlerFunc turns a function with the right signature into a l i s t networkranges handler
type LISTNetworkrangesHandlerFunc func(LISTNetworkrangesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LISTNetworkrangesHandlerFunc) Handle(params LISTNetworkrangesParams) middleware.Responder {
	return fn(params)
}

// LISTNetworkrangesHandler interface for that can handle valid l i s t networkranges params
type LISTNetworkrangesHandler interface {
	Handle(LISTNetworkrangesParams) middleware.Responder
}

// NewLISTNetworkranges creates a new http.Handler for the l i s t networkranges operation
func NewLISTNetworkranges(ctx *middleware.Context, handler LISTNetworkrangesHandler) *LISTNetworkranges {
	return &LISTNetworkranges{Context: ctx, Handler: handler}
}

/*LISTNetworkranges swagger:route GET /networkranges Networkranges lISTNetworkranges

List Networkranges

*/
type LISTNetworkranges struct {
	Context *middleware.Context
	Handler LISTNetworkrangesHandler
}

func (o *LISTNetworkranges) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewLISTNetworkrangesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
