package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTNetworkroutersOK l i s t networkrouters o k

swagger:response lISTNetworkroutersOK
*/
type LISTNetworkroutersOK struct {

	// In: body
	Payload []*models.NetworkrouterOutput `json:"body,omitempty"`
}

// NewLISTNetworkroutersOK creates LISTNetworkroutersOK with default headers values
func NewLISTNetworkroutersOK() *LISTNetworkroutersOK {
	return &LISTNetworkroutersOK{}
}

// WithPayload adds the payload to the l i s t networkrouters o k response
func (o *LISTNetworkroutersOK) WithPayload(payload []*models.NetworkrouterOutput) *LISTNetworkroutersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t networkrouters o k response
func (o *LISTNetworkroutersOK) SetPayload(payload []*models.NetworkrouterOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTNetworkroutersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
