package networkrouters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// POSTNetworkrouterHandlerFunc turns a function with the right signature into a p o s t networkrouter handler
type POSTNetworkrouterHandlerFunc func(POSTNetworkrouterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn POSTNetworkrouterHandlerFunc) Handle(params POSTNetworkrouterParams) middleware.Responder {
	return fn(params)
}

// POSTNetworkrouterHandler interface for that can handle valid p o s t networkrouter params
type POSTNetworkrouterHandler interface {
	Handle(POSTNetworkrouterParams) middleware.Responder
}

// NewPOSTNetworkrouter creates a new http.Handler for the p o s t networkrouter operation
func NewPOSTNetworkrouter(ctx *middleware.Context, handler POSTNetworkrouterHandler) *POSTNetworkrouter {
	return &POSTNetworkrouter{Context: ctx, Handler: handler}
}

/*POSTNetworkrouter swagger:route POST /networkrouters Networkrouters pOSTNetworkrouter

Create NetworkRouter

*/
type POSTNetworkrouter struct {
	Context *middleware.Context
	Handler POSTNetworkrouterHandler
}

func (o *POSTNetworkrouter) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPOSTNetworkrouterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
