package dnsnameentries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETDnsnameentriesOK g e t dnsnameentries o k

swagger:response gETDnsnameentriesOK
*/
type GETDnsnameentriesOK struct {

	// In: body
	Payload *models.DnsnameentriesOutput `json:"body,omitempty"`
}

// NewGETDnsnameentriesOK creates GETDnsnameentriesOK with default headers values
func NewGETDnsnameentriesOK() *GETDnsnameentriesOK {
	return &GETDnsnameentriesOK{}
}

// WithPayload adds the payload to the g e t dnsnameentries o k response
func (o *GETDnsnameentriesOK) WithPayload(payload *models.DnsnameentriesOutput) *GETDnsnameentriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t dnsnameentries o k response
func (o *GETDnsnameentriesOK) SetPayload(payload *models.DnsnameentriesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETDnsnameentriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
