package dnsnameentries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTDnsnameentriesCreated p o s t dnsnameentries created

swagger:response pOSTDnsnameentriesCreated
*/
type POSTDnsnameentriesCreated struct {

	// In: body
	Payload *models.DnsnameentriesOutput `json:"body,omitempty"`
}

// NewPOSTDnsnameentriesCreated creates POSTDnsnameentriesCreated with default headers values
func NewPOSTDnsnameentriesCreated() *POSTDnsnameentriesCreated {
	return &POSTDnsnameentriesCreated{}
}

// WithPayload adds the payload to the p o s t dnsnameentries created response
func (o *POSTDnsnameentriesCreated) WithPayload(payload *models.DnsnameentriesOutput) *POSTDnsnameentriesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t dnsnameentries created response
func (o *POSTDnsnameentriesCreated) SetPayload(payload *models.DnsnameentriesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTDnsnameentriesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
