package dnsnameentries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PUTDnsnameentriesHandlerFunc turns a function with the right signature into a p u t dnsnameentries handler
type PUTDnsnameentriesHandlerFunc func(PUTDnsnameentriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PUTDnsnameentriesHandlerFunc) Handle(params PUTDnsnameentriesParams) middleware.Responder {
	return fn(params)
}

// PUTDnsnameentriesHandler interface for that can handle valid p u t dnsnameentries params
type PUTDnsnameentriesHandler interface {
	Handle(PUTDnsnameentriesParams) middleware.Responder
}

// NewPUTDnsnameentries creates a new http.Handler for the p u t dnsnameentries operation
func NewPUTDnsnameentries(ctx *middleware.Context, handler PUTDnsnameentriesHandler) *PUTDnsnameentries {
	return &PUTDnsnameentries{Context: ctx, Handler: handler}
}

/*PUTDnsnameentries swagger:route PUT /dnsnameentries/{id} Dnsnameentries pUTDnsnameentries

Update DNSNameEntries

*/
type PUTDnsnameentries struct {
	Context *middleware.Context
	Handler PUTDnsnameentriesHandler
}

func (o *PUTDnsnameentries) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPUTDnsnameentriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
