package noderoles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETENoderoleReader is a Reader for the DELETENoderole structure.
type DELETENoderoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETENoderoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETENoderoleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETENoderoleNoContent creates a DELETENoderoleNoContent with default headers values
func NewDELETENoderoleNoContent() *DELETENoderoleNoContent {
	return &DELETENoderoleNoContent{}
}

/*DELETENoderoleNoContent handles this case with default header values.

DELETENoderoleNoContent d e l e t e noderole no content
*/
type DELETENoderoleNoContent struct {
}

func (o *DELETENoderoleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /noderoles/{id}][%d] dELETENoderoleNoContent ", 204)
}

func (o *DELETENoderoleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
