package noderoles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTNoderolesReader is a Reader for the LISTNoderoles structure.
type LISTNoderolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTNoderolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTNoderolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTNoderolesOK creates a LISTNoderolesOK with default headers values
func NewLISTNoderolesOK() *LISTNoderolesOK {
	return &LISTNoderolesOK{}
}

/*LISTNoderolesOK handles this case with default header values.

LISTNoderolesOK l i s t noderoles o k
*/
type LISTNoderolesOK struct {
	Payload []*models.NoderoleOutput
}

func (o *LISTNoderolesOK) Error() string {
	return fmt.Sprintf("[GET /noderoles][%d] lISTNoderolesOK  %+v", 200, o.Payload)
}

func (o *LISTNoderolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
