package noderoles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTNoderolesParams creates a new LISTNoderolesParams object
// with the default values initialized.
func NewLISTNoderolesParams() *LISTNoderolesParams {

	return &LISTNoderolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTNoderolesParamsWithTimeout creates a new LISTNoderolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTNoderolesParamsWithTimeout(timeout time.Duration) *LISTNoderolesParams {

	return &LISTNoderolesParams{

		timeout: timeout,
	}
}

// NewLISTNoderolesParamsWithContext creates a new LISTNoderolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTNoderolesParamsWithContext(ctx context.Context) *LISTNoderolesParams {

	return &LISTNoderolesParams{

		Context: ctx,
	}
}

/*LISTNoderolesParams contains all the parameters to send to the API endpoint
for the l i s t noderoles operation typically these are written to a http.Request
*/
type LISTNoderolesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t noderoles params
func (o *LISTNoderolesParams) WithTimeout(timeout time.Duration) *LISTNoderolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t noderoles params
func (o *LISTNoderolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t noderoles params
func (o *LISTNoderolesParams) WithContext(ctx context.Context) *LISTNoderolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t noderoles params
func (o *LISTNoderolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTNoderolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
