package noderoles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTNoderoleParams creates a new POSTNoderoleParams object
// with the default values initialized.
func NewPOSTNoderoleParams() *POSTNoderoleParams {
	var ()
	return &POSTNoderoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTNoderoleParamsWithTimeout creates a new POSTNoderoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTNoderoleParamsWithTimeout(timeout time.Duration) *POSTNoderoleParams {
	var ()
	return &POSTNoderoleParams{

		timeout: timeout,
	}
}

// NewPOSTNoderoleParamsWithContext creates a new POSTNoderoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTNoderoleParamsWithContext(ctx context.Context) *POSTNoderoleParams {
	var ()
	return &POSTNoderoleParams{

		Context: ctx,
	}
}

/*POSTNoderoleParams contains all the parameters to send to the API endpoint
for the p o s t noderole operation typically these are written to a http.Request
*/
type POSTNoderoleParams struct {

	/*Body*/
	Body *models.NoderoleInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t noderole params
func (o *POSTNoderoleParams) WithTimeout(timeout time.Duration) *POSTNoderoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t noderole params
func (o *POSTNoderoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t noderole params
func (o *POSTNoderoleParams) WithContext(ctx context.Context) *POSTNoderoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t noderole params
func (o *POSTNoderoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t noderole params
func (o *POSTNoderoleParams) WithBody(body *models.NoderoleInput) *POSTNoderoleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t noderole params
func (o *POSTNoderoleParams) SetBody(body *models.NoderoleInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTNoderoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NoderoleInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
