package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETENodeReader is a Reader for the DELETENode structure.
type DELETENodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETENodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETENodeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETENodeNoContent creates a DELETENodeNoContent with default headers values
func NewDELETENodeNoContent() *DELETENodeNoContent {
	return &DELETENodeNoContent{}
}

/*DELETENodeNoContent handles this case with default header values.

DELETENodeNoContent d e l e t e node no content
*/
type DELETENodeNoContent struct {
}

func (o *DELETENodeNoContent) Error() string {
	return fmt.Sprintf("[DELETE /nodes/{id}][%d] dELETENodeNoContent ", 204)
}

func (o *DELETENodeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
