package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETNodeParams creates a new GETNodeParams object
// with the default values initialized.
func NewGETNodeParams() *GETNodeParams {
	var ()
	return &GETNodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETNodeParamsWithTimeout creates a new GETNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETNodeParamsWithTimeout(timeout time.Duration) *GETNodeParams {
	var ()
	return &GETNodeParams{

		timeout: timeout,
	}
}

// NewGETNodeParamsWithContext creates a new GETNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETNodeParamsWithContext(ctx context.Context) *GETNodeParams {
	var ()
	return &GETNodeParams{

		Context: ctx,
	}
}

/*GETNodeParams contains all the parameters to send to the API endpoint
for the g e t node operation typically these are written to a http.Request
*/
type GETNodeParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t node params
func (o *GETNodeParams) WithTimeout(timeout time.Duration) *GETNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t node params
func (o *GETNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t node params
func (o *GETNodeParams) WithContext(ctx context.Context) *GETNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t node params
func (o *GETNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t node params
func (o *GETNodeParams) WithID(id string) *GETNodeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t node params
func (o *GETNodeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
