package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTNodesReader is a Reader for the LISTNodes structure.
type LISTNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTNodesOK creates a LISTNodesOK with default headers values
func NewLISTNodesOK() *LISTNodesOK {
	return &LISTNodesOK{}
}

/*LISTNodesOK handles this case with default header values.

LISTNodesOK l i s t nodes o k
*/
type LISTNodesOK struct {
	Payload []*models.NodeOutput
}

func (o *LISTNodesOK) Error() string {
	return fmt.Sprintf("[GET /nodes][%d] lISTNodesOK  %+v", 200, o.Payload)
}

func (o *LISTNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
