package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTNodesParams creates a new LISTNodesParams object
// with the default values initialized.
func NewLISTNodesParams() *LISTNodesParams {

	return &LISTNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTNodesParamsWithTimeout creates a new LISTNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTNodesParamsWithTimeout(timeout time.Duration) *LISTNodesParams {

	return &LISTNodesParams{

		timeout: timeout,
	}
}

// NewLISTNodesParamsWithContext creates a new LISTNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTNodesParamsWithContext(ctx context.Context) *LISTNodesParams {

	return &LISTNodesParams{

		Context: ctx,
	}
}

/*LISTNodesParams contains all the parameters to send to the API endpoint
for the l i s t nodes operation typically these are written to a http.Request
*/
type LISTNodesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t nodes params
func (o *LISTNodesParams) WithTimeout(timeout time.Duration) *LISTNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t nodes params
func (o *LISTNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t nodes params
func (o *LISTNodesParams) WithContext(ctx context.Context) *LISTNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t nodes params
func (o *LISTNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
