package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPATCHNodeParams creates a new PATCHNodeParams object
// with the default values initialized.
func NewPATCHNodeParams() *PATCHNodeParams {

	return &PATCHNodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPATCHNodeParamsWithTimeout creates a new PATCHNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPATCHNodeParamsWithTimeout(timeout time.Duration) *PATCHNodeParams {

	return &PATCHNodeParams{

		timeout: timeout,
	}
}

// NewPATCHNodeParamsWithContext creates a new PATCHNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPATCHNodeParamsWithContext(ctx context.Context) *PATCHNodeParams {

	return &PATCHNodeParams{

		Context: ctx,
	}
}

/*PATCHNodeParams contains all the parameters to send to the API endpoint
for the p a t c h node operation typically these are written to a http.Request
*/
type PATCHNodeParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p a t c h node params
func (o *PATCHNodeParams) WithTimeout(timeout time.Duration) *PATCHNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p a t c h node params
func (o *PATCHNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p a t c h node params
func (o *PATCHNodeParams) WithContext(ctx context.Context) *PATCHNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p a t c h node params
func (o *PATCHNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *PATCHNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
