package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTNodeParams creates a new POSTNodeParams object
// with the default values initialized.
func NewPOSTNodeParams() *POSTNodeParams {
	var ()
	return &POSTNodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTNodeParamsWithTimeout creates a new POSTNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTNodeParamsWithTimeout(timeout time.Duration) *POSTNodeParams {
	var ()
	return &POSTNodeParams{

		timeout: timeout,
	}
}

// NewPOSTNodeParamsWithContext creates a new POSTNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTNodeParamsWithContext(ctx context.Context) *POSTNodeParams {
	var ()
	return &POSTNodeParams{

		Context: ctx,
	}
}

/*POSTNodeParams contains all the parameters to send to the API endpoint
for the p o s t node operation typically these are written to a http.Request
*/
type POSTNodeParams struct {

	/*Body*/
	Body *models.NodeInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t node params
func (o *POSTNodeParams) WithTimeout(timeout time.Duration) *POSTNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t node params
func (o *POSTNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t node params
func (o *POSTNodeParams) WithContext(ctx context.Context) *POSTNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t node params
func (o *POSTNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t node params
func (o *POSTNodeParams) WithBody(body *models.NodeInput) *POSTNodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t node params
func (o *POSTNodeParams) SetBody(body *models.NodeInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NodeInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
