package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// PUTNodeReader is a Reader for the PUTNode structure.
type PUTNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PUTNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPUTNodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPUTNodeOK creates a PUTNodeOK with default headers values
func NewPUTNodeOK() *PUTNodeOK {
	return &PUTNodeOK{}
}

/*PUTNodeOK handles this case with default header values.

PUTNodeOK p u t node o k
*/
type PUTNodeOK struct {
	Payload *models.NodeOutput
}

func (o *PUTNodeOK) Error() string {
	return fmt.Sprintf("[PUT /nodes/{id}][%d] pUTNodeOK  %+v", 200, o.Payload)
}

func (o *PUTNodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodeOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
