package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTNodeParams creates a new PUTNodeParams object
// with the default values initialized.
func NewPUTNodeParams() *PUTNodeParams {
	var ()
	return &PUTNodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTNodeParamsWithTimeout creates a new PUTNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTNodeParamsWithTimeout(timeout time.Duration) *PUTNodeParams {
	var ()
	return &PUTNodeParams{

		timeout: timeout,
	}
}

// NewPUTNodeParamsWithContext creates a new PUTNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTNodeParamsWithContext(ctx context.Context) *PUTNodeParams {
	var ()
	return &PUTNodeParams{

		Context: ctx,
	}
}

/*PUTNodeParams contains all the parameters to send to the API endpoint
for the p u t node operation typically these are written to a http.Request
*/
type PUTNodeParams struct {

	/*Body*/
	Body *models.NodeInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t node params
func (o *PUTNodeParams) WithTimeout(timeout time.Duration) *PUTNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t node params
func (o *PUTNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t node params
func (o *PUTNodeParams) WithContext(ctx context.Context) *PUTNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t node params
func (o *PUTNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t node params
func (o *PUTNodeParams) WithBody(body *models.NodeInput) *PUTNodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t node params
func (o *PUTNodeParams) SetBody(body *models.NodeInput) {
	o.Body = body
}

// WithID adds the id to the p u t node params
func (o *PUTNodeParams) WithID(id string) *PUTNodeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t node params
func (o *PUTNodeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NodeInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
