package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEUserReader is a Reader for the DELETEUser structure.
type DELETEUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEUserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEUserNoContent creates a DELETEUserNoContent with default headers values
func NewDELETEUserNoContent() *DELETEUserNoContent {
	return &DELETEUserNoContent{}
}

/*DELETEUserNoContent handles this case with default header values.

DELETEUserNoContent d e l e t e user no content
*/
type DELETEUserNoContent struct {
}

func (o *DELETEUserNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] dELETEUserNoContent ", 204)
}

func (o *DELETEUserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
