package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEEventselectorParams creates a new DELETEEventselectorParams object
// with the default values initialized.
func NewDELETEEventselectorParams() *DELETEEventselectorParams {
	var ()
	return &DELETEEventselectorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEEventselectorParamsWithTimeout creates a new DELETEEventselectorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEEventselectorParamsWithTimeout(timeout time.Duration) *DELETEEventselectorParams {
	var ()
	return &DELETEEventselectorParams{

		timeout: timeout,
	}
}

// NewDELETEEventselectorParamsWithContext creates a new DELETEEventselectorParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEEventselectorParamsWithContext(ctx context.Context) *DELETEEventselectorParams {
	var ()
	return &DELETEEventselectorParams{

		Context: ctx,
	}
}

/*DELETEEventselectorParams contains all the parameters to send to the API endpoint
for the d e l e t e eventselector operation typically these are written to a http.Request
*/
type DELETEEventselectorParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) WithTimeout(timeout time.Duration) *DELETEEventselectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) WithContext(ctx context.Context) *DELETEEventselectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) WithID(id string) *DELETEEventselectorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e eventselector params
func (o *DELETEEventselectorParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEEventselectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
