package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEEventselectorReader is a Reader for the DELETEEventselector structure.
type DELETEEventselectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEEventselectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEEventselectorNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEEventselectorNoContent creates a DELETEEventselectorNoContent with default headers values
func NewDELETEEventselectorNoContent() *DELETEEventselectorNoContent {
	return &DELETEEventselectorNoContent{}
}

/*DELETEEventselectorNoContent handles this case with default header values.

DELETEEventselectorNoContent d e l e t e eventselector no content
*/
type DELETEEventselectorNoContent struct {
}

func (o *DELETEEventselectorNoContent) Error() string {
	return fmt.Sprintf("[DELETE /eventselectors/{id}][%d] dELETEEventselectorNoContent ", 204)
}

func (o *DELETEEventselectorNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
