package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETEventselectorReader is a Reader for the GETEventselector structure.
type GETEventselectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETEventselectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETEventselectorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETEventselectorOK creates a GETEventselectorOK with default headers values
func NewGETEventselectorOK() *GETEventselectorOK {
	return &GETEventselectorOK{}
}

/*GETEventselectorOK handles this case with default header values.

GETEventselectorOK g e t eventselector o k
*/
type GETEventselectorOK struct {
	Payload *models.EventselectorOutput
}

func (o *GETEventselectorOK) Error() string {
	return fmt.Sprintf("[GET /eventselectors/{id}][%d] gETEventselectorOK  %+v", 200, o.Payload)
}

func (o *GETEventselectorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventselectorOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
