package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTEventselectorReader is a Reader for the POSTEventselector structure.
type POSTEventselectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTEventselectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTEventselectorCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTEventselectorCreated creates a POSTEventselectorCreated with default headers values
func NewPOSTEventselectorCreated() *POSTEventselectorCreated {
	return &POSTEventselectorCreated{}
}

/*POSTEventselectorCreated handles this case with default header values.

POSTEventselectorCreated p o s t eventselector created
*/
type POSTEventselectorCreated struct {
	Payload *models.EventselectorOutput
}

func (o *POSTEventselectorCreated) Error() string {
	return fmt.Sprintf("[POST /eventselectors][%d] pOSTEventselectorCreated  %+v", 201, o.Payload)
}

func (o *POSTEventselectorCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventselectorOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
