package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// POSTEventselectorHandlerFunc turns a function with the right signature into a p o s t eventselector handler
type POSTEventselectorHandlerFunc func(POSTEventselectorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn POSTEventselectorHandlerFunc) Handle(params POSTEventselectorParams) middleware.Responder {
	return fn(params)
}

// POSTEventselectorHandler interface for that can handle valid p o s t eventselector params
type POSTEventselectorHandler interface {
	Handle(POSTEventselectorParams) middleware.Responder
}

// NewPOSTEventselector creates a new http.Handler for the p o s t eventselector operation
func NewPOSTEventselector(ctx *middleware.Context, handler POSTEventselectorHandler) *POSTEventselector {
	return &POSTEventselector{Context: ctx, Handler: handler}
}

/*POSTEventselector swagger:route POST /eventselectors Eventselectors pOSTEventselector

Create EventSelector

*/
type POSTEventselector struct {
	Context *middleware.Context
	Handler POSTEventselectorHandler
}

func (o *POSTEventselector) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPOSTEventselectorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
