package eventselectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*PUTEventselectorOK p u t eventselector o k

swagger:response pUTEventselectorOK
*/
type PUTEventselectorOK struct {

	// In: body
	Payload *models.EventselectorOutput `json:"body,omitempty"`
}

// NewPUTEventselectorOK creates PUTEventselectorOK with default headers values
func NewPUTEventselectorOK() *PUTEventselectorOK {
	return &PUTEventselectorOK{}
}

// WithPayload adds the payload to the p u t eventselector o k response
func (o *PUTEventselectorOK) WithPayload(payload *models.EventselectorOutput) *PUTEventselectorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p u t eventselector o k response
func (o *PUTEventselectorOK) SetPayload(payload *models.EventselectorOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PUTEventselectorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
