package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETCapabilitiesOK g e t capabilities o k

swagger:response gETCapabilitiesOK
*/
type GETCapabilitiesOK struct {

	// In: body
	Payload *models.CapabilitiesOutput `json:"body,omitempty"`
}

// NewGETCapabilitiesOK creates GETCapabilitiesOK with default headers values
func NewGETCapabilitiesOK() *GETCapabilitiesOK {
	return &GETCapabilitiesOK{}
}

// WithPayload adds the payload to the g e t capabilities o k response
func (o *GETCapabilitiesOK) WithPayload(payload *models.CapabilitiesOutput) *GETCapabilitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t capabilities o k response
func (o *GETCapabilitiesOK) SetPayload(payload *models.CapabilitiesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETCapabilitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
