package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTCapabilitiesOK l i s t capabilities o k

swagger:response lISTCapabilitiesOK
*/
type LISTCapabilitiesOK struct {

	// In: body
	Payload []*models.CapabilitiesOutput `json:"body,omitempty"`
}

// NewLISTCapabilitiesOK creates LISTCapabilitiesOK with default headers values
func NewLISTCapabilitiesOK() *LISTCapabilitiesOK {
	return &LISTCapabilitiesOK{}
}

// WithPayload adds the payload to the l i s t capabilities o k response
func (o *LISTCapabilitiesOK) WithPayload(payload []*models.CapabilitiesOutput) *LISTCapabilitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t capabilities o k response
func (o *LISTCapabilitiesOK) SetPayload(payload []*models.CapabilitiesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTCapabilitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
