package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTCapabilitiesCreated p o s t capabilities created

swagger:response pOSTCapabilitiesCreated
*/
type POSTCapabilitiesCreated struct {

	// In: body
	Payload *models.CapabilitiesOutput `json:"body,omitempty"`
}

// NewPOSTCapabilitiesCreated creates POSTCapabilitiesCreated with default headers values
func NewPOSTCapabilitiesCreated() *POSTCapabilitiesCreated {
	return &POSTCapabilitiesCreated{}
}

// WithPayload adds the payload to the p o s t capabilities created response
func (o *POSTCapabilitiesCreated) WithPayload(payload *models.CapabilitiesOutput) *POSTCapabilitiesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t capabilities created response
func (o *POSTCapabilitiesCreated) SetPayload(payload *models.CapabilitiesOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTCapabilitiesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
