package deploymentroles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEDeploymentrolesParams creates a new DELETEDeploymentrolesParams object
// with the default values initialized.
func NewDELETEDeploymentrolesParams() *DELETEDeploymentrolesParams {
	var ()
	return &DELETEDeploymentrolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEDeploymentrolesParamsWithTimeout creates a new DELETEDeploymentrolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEDeploymentrolesParamsWithTimeout(timeout time.Duration) *DELETEDeploymentrolesParams {
	var ()
	return &DELETEDeploymentrolesParams{

		timeout: timeout,
	}
}

// NewDELETEDeploymentrolesParamsWithContext creates a new DELETEDeploymentrolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEDeploymentrolesParamsWithContext(ctx context.Context) *DELETEDeploymentrolesParams {
	var ()
	return &DELETEDeploymentrolesParams{

		Context: ctx,
	}
}

/*DELETEDeploymentrolesParams contains all the parameters to send to the API endpoint
for the d e l e t e deploymentroles operation typically these are written to a http.Request
*/
type DELETEDeploymentrolesParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) WithTimeout(timeout time.Duration) *DELETEDeploymentrolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) WithContext(ctx context.Context) *DELETEDeploymentrolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) WithID(id string) *DELETEDeploymentrolesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e deploymentroles params
func (o *DELETEDeploymentrolesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEDeploymentrolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
