package deploymentroles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETDeploymentrolesParams creates a new GETDeploymentrolesParams object
// with the default values initialized.
func NewGETDeploymentrolesParams() *GETDeploymentrolesParams {
	var ()
	return &GETDeploymentrolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETDeploymentrolesParamsWithTimeout creates a new GETDeploymentrolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETDeploymentrolesParamsWithTimeout(timeout time.Duration) *GETDeploymentrolesParams {
	var ()
	return &GETDeploymentrolesParams{

		timeout: timeout,
	}
}

// NewGETDeploymentrolesParamsWithContext creates a new GETDeploymentrolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETDeploymentrolesParamsWithContext(ctx context.Context) *GETDeploymentrolesParams {
	var ()
	return &GETDeploymentrolesParams{

		Context: ctx,
	}
}

/*GETDeploymentrolesParams contains all the parameters to send to the API endpoint
for the g e t deploymentroles operation typically these are written to a http.Request
*/
type GETDeploymentrolesParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) WithTimeout(timeout time.Duration) *GETDeploymentrolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) WithContext(ctx context.Context) *GETDeploymentrolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) WithID(id string) *GETDeploymentrolesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t deploymentroles params
func (o *GETDeploymentrolesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETDeploymentrolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
