package deploymentroles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTDeploymentrolesParams creates a new LISTDeploymentrolesParams object
// with the default values initialized.
func NewLISTDeploymentrolesParams() *LISTDeploymentrolesParams {

	return &LISTDeploymentrolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTDeploymentrolesParamsWithTimeout creates a new LISTDeploymentrolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTDeploymentrolesParamsWithTimeout(timeout time.Duration) *LISTDeploymentrolesParams {

	return &LISTDeploymentrolesParams{

		timeout: timeout,
	}
}

// NewLISTDeploymentrolesParamsWithContext creates a new LISTDeploymentrolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTDeploymentrolesParamsWithContext(ctx context.Context) *LISTDeploymentrolesParams {

	return &LISTDeploymentrolesParams{

		Context: ctx,
	}
}

/*LISTDeploymentrolesParams contains all the parameters to send to the API endpoint
for the l i s t deploymentroles operation typically these are written to a http.Request
*/
type LISTDeploymentrolesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t deploymentroles params
func (o *LISTDeploymentrolesParams) WithTimeout(timeout time.Duration) *LISTDeploymentrolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t deploymentroles params
func (o *LISTDeploymentrolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t deploymentroles params
func (o *LISTDeploymentrolesParams) WithContext(ctx context.Context) *LISTDeploymentrolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t deploymentroles params
func (o *LISTDeploymentrolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTDeploymentrolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
