package deploymentroles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTDeploymentrolesReader is a Reader for the LISTDeploymentroles structure.
type LISTDeploymentrolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTDeploymentrolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTDeploymentrolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTDeploymentrolesOK creates a LISTDeploymentrolesOK with default headers values
func NewLISTDeploymentrolesOK() *LISTDeploymentrolesOK {
	return &LISTDeploymentrolesOK{}
}

/*LISTDeploymentrolesOK handles this case with default header values.

LISTDeploymentrolesOK l i s t deploymentroles o k
*/
type LISTDeploymentrolesOK struct {
	Payload []*models.DeploymentrolesOutput
}

func (o *LISTDeploymentrolesOK) Error() string {
	return fmt.Sprintf("[GET /deploymentroles][%d] lISTDeploymentrolesOK  %+v", 200, o.Payload)
}

func (o *LISTDeploymentrolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
