package noderoles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTNoderolesOK l i s t noderoles o k

swagger:response lISTNoderolesOK
*/
type LISTNoderolesOK struct {

	// In: body
	Payload []*models.NoderoleOutput `json:"body,omitempty"`
}

// NewLISTNoderolesOK creates LISTNoderolesOK with default headers values
func NewLISTNoderolesOK() *LISTNoderolesOK {
	return &LISTNoderolesOK{}
}

// WithPayload adds the payload to the l i s t noderoles o k response
func (o *LISTNoderolesOK) WithPayload(payload []*models.NoderoleOutput) *LISTNoderolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t noderoles o k response
func (o *LISTNoderolesOK) SetPayload(payload []*models.NoderoleOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTNoderolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
