package attribs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTAttribsOK l i s t attribs o k

swagger:response lISTAttribsOK
*/
type LISTAttribsOK struct {

	// In: body
	Payload []*models.AttribOutput `json:"body,omitempty"`
}

// NewLISTAttribsOK creates LISTAttribsOK with default headers values
func NewLISTAttribsOK() *LISTAttribsOK {
	return &LISTAttribsOK{}
}

// WithPayload adds the payload to the l i s t attribs o k response
func (o *LISTAttribsOK) WithPayload(payload []*models.AttribOutput) *LISTAttribsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t attribs o k response
func (o *LISTAttribsOK) SetPayload(payload []*models.AttribOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTAttribsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
