package attribs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PUTAttribHandlerFunc turns a function with the right signature into a p u t attrib handler
type PUTAttribHandlerFunc func(PUTAttribParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PUTAttribHandlerFunc) Handle(params PUTAttribParams) middleware.Responder {
	return fn(params)
}

// PUTAttribHandler interface for that can handle valid p u t attrib params
type PUTAttribHandler interface {
	Handle(PUTAttribParams) middleware.Responder
}

// NewPUTAttrib creates a new http.Handler for the p u t attrib operation
func NewPUTAttrib(ctx *middleware.Context, handler PUTAttribHandler) *PUTAttrib {
	return &PUTAttrib{Context: ctx, Handler: handler}
}

/*PUTAttrib swagger:route PUT /attribs/{id} Attribs pUTAttrib

Update Attrib

*/
type PUTAttrib struct {
	Context *middleware.Context
	Handler PUTAttribHandler
}

func (o *PUTAttrib) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPUTAttribParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
