package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEDeploymentsReader is a Reader for the DELETEDeployments structure.
type DELETEDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEDeploymentsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEDeploymentsNoContent creates a DELETEDeploymentsNoContent with default headers values
func NewDELETEDeploymentsNoContent() *DELETEDeploymentsNoContent {
	return &DELETEDeploymentsNoContent{}
}

/*DELETEDeploymentsNoContent handles this case with default header values.

DELETEDeploymentsNoContent d e l e t e deployments no content
*/
type DELETEDeploymentsNoContent struct {
}

func (o *DELETEDeploymentsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /deployments/{id}][%d] dELETEDeploymentsNoContent ", 204)
}

func (o *DELETEDeploymentsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
