package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETDeploymentsReader is a Reader for the GETDeployments structure.
type GETDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETDeploymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETDeploymentsOK creates a GETDeploymentsOK with default headers values
func NewGETDeploymentsOK() *GETDeploymentsOK {
	return &GETDeploymentsOK{}
}

/*GETDeploymentsOK handles this case with default header values.

GETDeploymentsOK g e t deployments o k
*/
type GETDeploymentsOK struct {
	Payload *models.DeploymentsOutput
}

func (o *GETDeploymentsOK) Error() string {
	return fmt.Sprintf("[GET /deployments/{id}][%d] gETDeploymentsOK  %+v", 200, o.Payload)
}

func (o *GETDeploymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentsOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
