package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTDeploymentsParams creates a new LISTDeploymentsParams object
// with the default values initialized.
func NewLISTDeploymentsParams() *LISTDeploymentsParams {

	return &LISTDeploymentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTDeploymentsParamsWithTimeout creates a new LISTDeploymentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTDeploymentsParamsWithTimeout(timeout time.Duration) *LISTDeploymentsParams {

	return &LISTDeploymentsParams{

		timeout: timeout,
	}
}

// NewLISTDeploymentsParamsWithContext creates a new LISTDeploymentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTDeploymentsParamsWithContext(ctx context.Context) *LISTDeploymentsParams {

	return &LISTDeploymentsParams{

		Context: ctx,
	}
}

/*LISTDeploymentsParams contains all the parameters to send to the API endpoint
for the l i s t deployments operation typically these are written to a http.Request
*/
type LISTDeploymentsParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t deployments params
func (o *LISTDeploymentsParams) WithTimeout(timeout time.Duration) *LISTDeploymentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t deployments params
func (o *LISTDeploymentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t deployments params
func (o *LISTDeploymentsParams) WithContext(ctx context.Context) *LISTDeploymentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t deployments params
func (o *LISTDeploymentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTDeploymentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
