package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTDeploymentsReader is a Reader for the POSTDeployments structure.
type POSTDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTDeploymentsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTDeploymentsCreated creates a POSTDeploymentsCreated with default headers values
func NewPOSTDeploymentsCreated() *POSTDeploymentsCreated {
	return &POSTDeploymentsCreated{}
}

/*POSTDeploymentsCreated handles this case with default header values.

POSTDeploymentsCreated p o s t deployments created
*/
type POSTDeploymentsCreated struct {
	Payload *models.DeploymentsOutput
}

func (o *POSTDeploymentsCreated) Error() string {
	return fmt.Sprintf("[POST /deployments][%d] pOSTDeploymentsCreated  %+v", 201, o.Payload)
}

func (o *POSTDeploymentsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentsOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
