package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETProfileParams creates a new GETProfileParams object
// with the default values initialized.
func NewGETProfileParams() *GETProfileParams {
	var ()
	return &GETProfileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETProfileParamsWithTimeout creates a new GETProfileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETProfileParamsWithTimeout(timeout time.Duration) *GETProfileParams {
	var ()
	return &GETProfileParams{

		timeout: timeout,
	}
}

// NewGETProfileParamsWithContext creates a new GETProfileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETProfileParamsWithContext(ctx context.Context) *GETProfileParams {
	var ()
	return &GETProfileParams{

		Context: ctx,
	}
}

/*GETProfileParams contains all the parameters to send to the API endpoint
for the g e t profile operation typically these are written to a http.Request
*/
type GETProfileParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the g e t profile params
func (o *GETProfileParams) WithTimeout(timeout time.Duration) *GETProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t profile params
func (o *GETProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t profile params
func (o *GETProfileParams) WithContext(ctx context.Context) *GETProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t profile params
func (o *GETProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the g e t profile params
func (o *GETProfileParams) WithID(id string) *GETProfileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t profile params
func (o *GETProfileParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
