package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTProfileReader is a Reader for the POSTProfile structure.
type POSTProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTProfileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTProfileCreated creates a POSTProfileCreated with default headers values
func NewPOSTProfileCreated() *POSTProfileCreated {
	return &POSTProfileCreated{}
}

/*POSTProfileCreated handles this case with default header values.

POSTProfileCreated p o s t profile created
*/
type POSTProfileCreated struct {
	Payload *models.ProfileOutput
}

func (o *POSTProfileCreated) Error() string {
	return fmt.Sprintf("[POST /profiles][%d] pOSTProfileCreated  %+v", 201, o.Payload)
}

func (o *POSTProfileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProfileOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
