package barclamps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEBarclampParams creates a new DELETEBarclampParams object
// with the default values initialized.
func NewDELETEBarclampParams() *DELETEBarclampParams {
	var ()
	return &DELETEBarclampParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEBarclampParamsWithTimeout creates a new DELETEBarclampParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEBarclampParamsWithTimeout(timeout time.Duration) *DELETEBarclampParams {
	var ()
	return &DELETEBarclampParams{

		timeout: timeout,
	}
}

// NewDELETEBarclampParamsWithContext creates a new DELETEBarclampParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEBarclampParamsWithContext(ctx context.Context) *DELETEBarclampParams {
	var ()
	return &DELETEBarclampParams{

		Context: ctx,
	}
}

/*DELETEBarclampParams contains all the parameters to send to the API endpoint
for the d e l e t e barclamp operation typically these are written to a http.Request
*/
type DELETEBarclampParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e barclamp params
func (o *DELETEBarclampParams) WithTimeout(timeout time.Duration) *DELETEBarclampParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e barclamp params
func (o *DELETEBarclampParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e barclamp params
func (o *DELETEBarclampParams) WithContext(ctx context.Context) *DELETEBarclampParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e barclamp params
func (o *DELETEBarclampParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e barclamp params
func (o *DELETEBarclampParams) WithID(id string) *DELETEBarclampParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e barclamp params
func (o *DELETEBarclampParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEBarclampParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
