package barclamps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// GETBarclampReader is a Reader for the GETBarclamp structure.
type GETBarclampReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETBarclampReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETBarclampOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETBarclampOK creates a GETBarclampOK with default headers values
func NewGETBarclampOK() *GETBarclampOK {
	return &GETBarclampOK{}
}

/*GETBarclampOK handles this case with default header values.

GETBarclampOK g e t barclamp o k
*/
type GETBarclampOK struct {
	Payload *models.BarclampOutput
}

func (o *GETBarclampOK) Error() string {
	return fmt.Sprintf("[GET /barclamps/{id}][%d] gETBarclampOK  %+v", 200, o.Payload)
}

func (o *GETBarclampOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BarclampOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
