package barclamps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTBarclampReader is a Reader for the POSTBarclamp structure.
type POSTBarclampReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTBarclampReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTBarclampCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTBarclampCreated creates a POSTBarclampCreated with default headers values
func NewPOSTBarclampCreated() *POSTBarclampCreated {
	return &POSTBarclampCreated{}
}

/*POSTBarclampCreated handles this case with default header values.

POSTBarclampCreated p o s t barclamp created
*/
type POSTBarclampCreated struct {
	Payload *models.BarclampOutput
}

func (o *POSTBarclampCreated) Error() string {
	return fmt.Sprintf("[POST /barclamps][%d] pOSTBarclampCreated  %+v", 201, o.Payload)
}

func (o *POSTBarclampCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BarclampOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
