package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*LISTNetworkallocationsOK l i s t networkallocations o k

swagger:response lISTNetworkallocationsOK
*/
type LISTNetworkallocationsOK struct {

	// In: body
	Payload []*models.NetworkallocationOutput `json:"body,omitempty"`
}

// NewLISTNetworkallocationsOK creates LISTNetworkallocationsOK with default headers values
func NewLISTNetworkallocationsOK() *LISTNetworkallocationsOK {
	return &LISTNetworkallocationsOK{}
}

// WithPayload adds the payload to the l i s t networkallocations o k response
func (o *LISTNetworkallocationsOK) WithPayload(payload []*models.NetworkallocationOutput) *LISTNetworkallocationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t networkallocations o k response
func (o *LISTNetworkallocationsOK) SetPayload(payload []*models.NetworkallocationOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTNetworkallocationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
