package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTNetworkallocationCreated p o s t networkallocation created

swagger:response pOSTNetworkallocationCreated
*/
type POSTNetworkallocationCreated struct {

	// In: body
	Payload *models.NetworkallocationOutput `json:"body,omitempty"`
}

// NewPOSTNetworkallocationCreated creates POSTNetworkallocationCreated with default headers values
func NewPOSTNetworkallocationCreated() *POSTNetworkallocationCreated {
	return &POSTNetworkallocationCreated{}
}

// WithPayload adds the payload to the p o s t networkallocation created response
func (o *POSTNetworkallocationCreated) WithPayload(payload *models.NetworkallocationOutput) *POSTNetworkallocationCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t networkallocation created response
func (o *POSTNetworkallocationCreated) SetPayload(payload *models.NetworkallocationOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTNetworkallocationCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
