package networkallocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PUTNetworkallocationHandlerFunc turns a function with the right signature into a p u t networkallocation handler
type PUTNetworkallocationHandlerFunc func(PUTNetworkallocationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PUTNetworkallocationHandlerFunc) Handle(params PUTNetworkallocationParams) middleware.Responder {
	return fn(params)
}

// PUTNetworkallocationHandler interface for that can handle valid p u t networkallocation params
type PUTNetworkallocationHandler interface {
	Handle(PUTNetworkallocationParams) middleware.Responder
}

// NewPUTNetworkallocation creates a new http.Handler for the p u t networkallocation operation
func NewPUTNetworkallocation(ctx *middleware.Context, handler PUTNetworkallocationHandler) *PUTNetworkallocation {
	return &PUTNetworkallocation{Context: ctx, Handler: handler}
}

/*PUTNetworkallocation swagger:route PUT /networkallocations/{id} Networkallocations pUTNetworkallocation

Update NetworkAllocation

*/
type PUTNetworkallocation struct {
	Context *middleware.Context
	Handler PUTNetworkallocationHandler
}

func (o *PUTNetworkallocation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPUTNetworkallocationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
