package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DELETEUserHandlerFunc turns a function with the right signature into a d e l e t e user handler
type DELETEUserHandlerFunc func(DELETEUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DELETEUserHandlerFunc) Handle(params DELETEUserParams) middleware.Responder {
	return fn(params)
}

// DELETEUserHandler interface for that can handle valid d e l e t e user params
type DELETEUserHandler interface {
	Handle(DELETEUserParams) middleware.Responder
}

// NewDELETEUser creates a new http.Handler for the d e l e t e user operation
func NewDELETEUser(ctx *middleware.Context, handler DELETEUserHandler) *DELETEUser {
	return &DELETEUser{Context: ctx, Handler: handler}
}

/*DELETEUser swagger:route DELETE /users/{id} Users dELETEUser

Delete User

*/
type DELETEUser struct {
	Context *middleware.Context
	Handler DELETEUserHandler
}

func (o *DELETEUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDELETEUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
