package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTUserCreated p o s t user created

swagger:response pOSTUserCreated
*/
type POSTUserCreated struct {

	// In: body
	Payload *models.UserOutput `json:"body,omitempty"`
}

// NewPOSTUserCreated creates POSTUserCreated with default headers values
func NewPOSTUserCreated() *POSTUserCreated {
	return &POSTUserCreated{}
}

// WithPayload adds the payload to the p o s t user created response
func (o *POSTUserCreated) WithPayload(payload *models.UserOutput) *POSTUserCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t user created response
func (o *POSTUserCreated) SetPayload(payload *models.UserOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
