package eventsinks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEEventsinkParams creates a new DELETEEventsinkParams object
// with the default values initialized.
func NewDELETEEventsinkParams() *DELETEEventsinkParams {
	var ()
	return &DELETEEventsinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEEventsinkParamsWithTimeout creates a new DELETEEventsinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEEventsinkParamsWithTimeout(timeout time.Duration) *DELETEEventsinkParams {
	var ()
	return &DELETEEventsinkParams{

		timeout: timeout,
	}
}

// NewDELETEEventsinkParamsWithContext creates a new DELETEEventsinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEEventsinkParamsWithContext(ctx context.Context) *DELETEEventsinkParams {
	var ()
	return &DELETEEventsinkParams{

		Context: ctx,
	}
}

/*DELETEEventsinkParams contains all the parameters to send to the API endpoint
for the d e l e t e eventsink operation typically these are written to a http.Request
*/
type DELETEEventsinkParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) WithTimeout(timeout time.Duration) *DELETEEventsinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) WithContext(ctx context.Context) *DELETEEventsinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) WithID(id string) *DELETEEventsinkParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e eventsink params
func (o *DELETEEventsinkParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEEventsinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
