package eventsinks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEEventsinkReader is a Reader for the DELETEEventsink structure.
type DELETEEventsinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEEventsinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEEventsinkNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEEventsinkNoContent creates a DELETEEventsinkNoContent with default headers values
func NewDELETEEventsinkNoContent() *DELETEEventsinkNoContent {
	return &DELETEEventsinkNoContent{}
}

/*DELETEEventsinkNoContent handles this case with default header values.

DELETEEventsinkNoContent d e l e t e eventsink no content
*/
type DELETEEventsinkNoContent struct {
}

func (o *DELETEEventsinkNoContent) Error() string {
	return fmt.Sprintf("[DELETE /eventsinks/{id}][%d] dELETEEventsinkNoContent ", 204)
}

func (o *DELETEEventsinkNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
