package eventsinks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// PUTEventsinkReader is a Reader for the PUTEventsink structure.
type PUTEventsinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PUTEventsinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPUTEventsinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPUTEventsinkOK creates a PUTEventsinkOK with default headers values
func NewPUTEventsinkOK() *PUTEventsinkOK {
	return &PUTEventsinkOK{}
}

/*PUTEventsinkOK handles this case with default header values.

PUTEventsinkOK p u t eventsink o k
*/
type PUTEventsinkOK struct {
	Payload *models.EventsinkOutput
}

func (o *PUTEventsinkOK) Error() string {
	return fmt.Sprintf("[PUT /eventsinks/{id}][%d] pUTEventsinkOK  %+v", 200, o.Payload)
}

func (o *PUTEventsinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventsinkOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
