package eventsinks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPUTEventsinkParams creates a new PUTEventsinkParams object
// with the default values initialized.
func NewPUTEventsinkParams() *PUTEventsinkParams {
	var ()
	return &PUTEventsinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTEventsinkParamsWithTimeout creates a new PUTEventsinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTEventsinkParamsWithTimeout(timeout time.Duration) *PUTEventsinkParams {
	var ()
	return &PUTEventsinkParams{

		timeout: timeout,
	}
}

// NewPUTEventsinkParamsWithContext creates a new PUTEventsinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTEventsinkParamsWithContext(ctx context.Context) *PUTEventsinkParams {
	var ()
	return &PUTEventsinkParams{

		Context: ctx,
	}
}

/*PUTEventsinkParams contains all the parameters to send to the API endpoint
for the p u t eventsink operation typically these are written to a http.Request
*/
type PUTEventsinkParams struct {

	/*Body*/
	Body *models.EventsinkInput
	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p u t eventsink params
func (o *PUTEventsinkParams) WithTimeout(timeout time.Duration) *PUTEventsinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t eventsink params
func (o *PUTEventsinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t eventsink params
func (o *PUTEventsinkParams) WithContext(ctx context.Context) *PUTEventsinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t eventsink params
func (o *PUTEventsinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t eventsink params
func (o *PUTEventsinkParams) WithBody(body *models.EventsinkInput) *PUTEventsinkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t eventsink params
func (o *PUTEventsinkParams) SetBody(body *models.EventsinkInput) {
	o.Body = body
}

// WithID adds the id to the p u t eventsink params
func (o *PUTEventsinkParams) WithID(id string) *PUTEventsinkParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t eventsink params
func (o *PUTEventsinkParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTEventsinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.EventsinkInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
