package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*GETHammerOK g e t hammer o k

swagger:response gETHammerOK
*/
type GETHammerOK struct {

	// In: body
	Payload *models.HammerOutput `json:"body,omitempty"`
}

// NewGETHammerOK creates GETHammerOK with default headers values
func NewGETHammerOK() *GETHammerOK {
	return &GETHammerOK{}
}

// WithPayload adds the payload to the g e t hammer o k response
func (o *GETHammerOK) WithPayload(payload *models.HammerOutput) *GETHammerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t hammer o k response
func (o *GETHammerOK) SetPayload(payload *models.HammerOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETHammerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
