package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GETHammerHandlerFunc turns a function with the right signature into a g e t hammer handler
type GETHammerHandlerFunc func(GETHammerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GETHammerHandlerFunc) Handle(params GETHammerParams) middleware.Responder {
	return fn(params)
}

// GETHammerHandler interface for that can handle valid g e t hammer params
type GETHammerHandler interface {
	Handle(GETHammerParams) middleware.Responder
}

// NewGETHammer creates a new http.Handler for the g e t hammer operation
func NewGETHammer(ctx *middleware.Context, handler GETHammerHandler) *GETHammer {
	return &GETHammer{Context: ctx, Handler: handler}
}

/*GETHammer swagger:route GET /hammers/{id} Hammers gETHammer

Get Hammer

*/
type GETHammer struct {
	Context *middleware.Context
	Handler GETHammerHandler
}

func (o *GETHammer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGETHammerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
