package hammers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

/*POSTHammerCreated p o s t hammer created

swagger:response pOSTHammerCreated
*/
type POSTHammerCreated struct {

	// In: body
	Payload *models.HammerOutput `json:"body,omitempty"`
}

// NewPOSTHammerCreated creates POSTHammerCreated with default headers values
func NewPOSTHammerCreated() *POSTHammerCreated {
	return &POSTHammerCreated{}
}

// WithPayload adds the payload to the p o s t hammer created response
func (o *POSTHammerCreated) WithPayload(payload *models.HammerOutput) *POSTHammerCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t hammer created response
func (o *POSTHammerCreated) SetPayload(payload *models.HammerOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTHammerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
