package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEUsertenantcapabilityParams creates a new DELETEUsertenantcapabilityParams object
// with the default values initialized.
func NewDELETEUsertenantcapabilityParams() *DELETEUsertenantcapabilityParams {
	var ()
	return &DELETEUsertenantcapabilityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEUsertenantcapabilityParamsWithTimeout creates a new DELETEUsertenantcapabilityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEUsertenantcapabilityParamsWithTimeout(timeout time.Duration) *DELETEUsertenantcapabilityParams {
	var ()
	return &DELETEUsertenantcapabilityParams{

		timeout: timeout,
	}
}

// NewDELETEUsertenantcapabilityParamsWithContext creates a new DELETEUsertenantcapabilityParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEUsertenantcapabilityParamsWithContext(ctx context.Context) *DELETEUsertenantcapabilityParams {
	var ()
	return &DELETEUsertenantcapabilityParams{

		Context: ctx,
	}
}

/*DELETEUsertenantcapabilityParams contains all the parameters to send to the API endpoint
for the d e l e t e usertenantcapability operation typically these are written to a http.Request
*/
type DELETEUsertenantcapabilityParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) WithTimeout(timeout time.Duration) *DELETEUsertenantcapabilityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) WithContext(ctx context.Context) *DELETEUsertenantcapabilityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) WithID(id string) *DELETEUsertenantcapabilityParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e usertenantcapability params
func (o *DELETEUsertenantcapabilityParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEUsertenantcapabilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
