package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEUsertenantcapabilityReader is a Reader for the DELETEUsertenantcapability structure.
type DELETEUsertenantcapabilityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEUsertenantcapabilityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEUsertenantcapabilityNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEUsertenantcapabilityNoContent creates a DELETEUsertenantcapabilityNoContent with default headers values
func NewDELETEUsertenantcapabilityNoContent() *DELETEUsertenantcapabilityNoContent {
	return &DELETEUsertenantcapabilityNoContent{}
}

/*DELETEUsertenantcapabilityNoContent handles this case with default header values.

DELETEUsertenantcapabilityNoContent d e l e t e usertenantcapability no content
*/
type DELETEUsertenantcapabilityNoContent struct {
}

func (o *DELETEUsertenantcapabilityNoContent) Error() string {
	return fmt.Sprintf("[DELETE /usertenantcapabilities/{id}][%d] dELETEUsertenantcapabilityNoContent ", 204)
}

func (o *DELETEUsertenantcapabilityNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
