package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTUsertenantcapabilitiesParams creates a new LISTUsertenantcapabilitiesParams object
// with the default values initialized.
func NewLISTUsertenantcapabilitiesParams() *LISTUsertenantcapabilitiesParams {

	return &LISTUsertenantcapabilitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTUsertenantcapabilitiesParamsWithTimeout creates a new LISTUsertenantcapabilitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTUsertenantcapabilitiesParamsWithTimeout(timeout time.Duration) *LISTUsertenantcapabilitiesParams {

	return &LISTUsertenantcapabilitiesParams{

		timeout: timeout,
	}
}

// NewLISTUsertenantcapabilitiesParamsWithContext creates a new LISTUsertenantcapabilitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTUsertenantcapabilitiesParamsWithContext(ctx context.Context) *LISTUsertenantcapabilitiesParams {

	return &LISTUsertenantcapabilitiesParams{

		Context: ctx,
	}
}

/*LISTUsertenantcapabilitiesParams contains all the parameters to send to the API endpoint
for the l i s t usertenantcapabilities operation typically these are written to a http.Request
*/
type LISTUsertenantcapabilitiesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the l i s t usertenantcapabilities params
func (o *LISTUsertenantcapabilitiesParams) WithTimeout(timeout time.Duration) *LISTUsertenantcapabilitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t usertenantcapabilities params
func (o *LISTUsertenantcapabilitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t usertenantcapabilities params
func (o *LISTUsertenantcapabilitiesParams) WithContext(ctx context.Context) *LISTUsertenantcapabilitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t usertenantcapabilities params
func (o *LISTUsertenantcapabilitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTUsertenantcapabilitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
