package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// LISTUsertenantcapabilitiesReader is a Reader for the LISTUsertenantcapabilities structure.
type LISTUsertenantcapabilitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LISTUsertenantcapabilitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLISTUsertenantcapabilitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLISTUsertenantcapabilitiesOK creates a LISTUsertenantcapabilitiesOK with default headers values
func NewLISTUsertenantcapabilitiesOK() *LISTUsertenantcapabilitiesOK {
	return &LISTUsertenantcapabilitiesOK{}
}

/*LISTUsertenantcapabilitiesOK handles this case with default header values.

LISTUsertenantcapabilitiesOK l i s t usertenantcapabilities o k
*/
type LISTUsertenantcapabilitiesOK struct {
	Payload []*models.UsertenantcapabilityOutput
}

func (o *LISTUsertenantcapabilitiesOK) Error() string {
	return fmt.Sprintf("[GET /usertenantcapabilities][%d] lISTUsertenantcapabilitiesOK  %+v", 200, o.Payload)
}

func (o *LISTUsertenantcapabilitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
