package usertenantcapabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTUsertenantcapabilityReader is a Reader for the POSTUsertenantcapability structure.
type POSTUsertenantcapabilityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTUsertenantcapabilityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTUsertenantcapabilityCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTUsertenantcapabilityCreated creates a POSTUsertenantcapabilityCreated with default headers values
func NewPOSTUsertenantcapabilityCreated() *POSTUsertenantcapabilityCreated {
	return &POSTUsertenantcapabilityCreated{}
}

/*POSTUsertenantcapabilityCreated handles this case with default header values.

POSTUsertenantcapabilityCreated p o s t usertenantcapability created
*/
type POSTUsertenantcapabilityCreated struct {
	Payload *models.UsertenantcapabilityOutput
}

func (o *POSTUsertenantcapabilityCreated) Error() string {
	return fmt.Sprintf("[POST /usertenantcapabilities][%d] pOSTUsertenantcapabilityCreated  %+v", 201, o.Payload)
}

func (o *POSTUsertenantcapabilityCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsertenantcapabilityOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
