package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DnsnamefiltersInput dnsnamefilters input
// swagger:model dnsnamefilters-input
type DnsnamefiltersInput struct {

	// matcher
	Matcher string `json:"matcher,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority int64 `json:"priority,omitempty"`

	// service
	Service string `json:"service,omitempty"`

	// template
	Template string `json:"template,omitempty"`

	// tenant id
	TenantID int64 `json:"tenant_id,omitempty"`
}

// Validate validates this dnsnamefilters input
func (m *DnsnamefiltersInput) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
