package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// HammerInput hammer input
// swagger:model hammer-input
type HammerInput struct {

	// actions
	Actions interface{} `json:"actions,omitempty"`

	// authenticator
	Authenticator string `json:"authenticator,omitempty"`

	// available hammer id
	AvailableHammerID int64 `json:"available_hammer_id,omitempty"`

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// node id
	NodeID int64 `json:"node_id,omitempty"`

	// priority
	Priority int64 `json:"priority,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this hammer input
func (m *HammerInput) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
