package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// NetworkallocationInput networkallocation input
// swagger:model networkallocation-input
type NetworkallocationInput struct {

	// address
	Address string `json:"address,omitempty"`

	// network id
	NetworkID int64 `json:"network_id,omitempty"`

	// network range id
	NetworkRangeID int64 `json:"network_range_id,omitempty"`

	// node id
	NodeID int64 `json:"node_id,omitempty"`

	// tenant id
	TenantID int64 `json:"tenant_id,omitempty"`
}

// Validate validates this networkallocation input
func (m *NetworkallocationInput) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
