package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// NetworkInput network input
// swagger:model network-input
type NetworkInput struct {

	// category
	Category string `json:"category,omitempty"`

	// conduit
	Conduit string `json:"conduit,omitempty"`

	// configure
	Configure bool `json:"configure,omitempty"`

	// deployment id
	DeploymentID int64 `json:"deployment_id,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// group
	Group string `json:"group,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pbr
	Pbr string `json:"pbr,omitempty"`

	// team mode
	TeamMode int64 `json:"team_mode,omitempty"`

	// tenant id
	TenantID int64 `json:"tenant_id,omitempty"`

	// use bridge
	UseBridge bool `json:"use_bridge,omitempty"`

	// use team
	UseTeam bool `json:"use_team,omitempty"`

	// use vlan
	UseVlan bool `json:"use_vlan,omitempty"`

	// v6prefix
	V6prefix string `json:"v6prefix,omitempty"`

	// vlan
	Vlan int64 `json:"vlan,omitempty"`
}

// Validate validates this network input
func (m *NetworkInput) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
