package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// NetworkrouterInput networkrouter input
// swagger:model networkrouter-input
type NetworkrouterInput struct {

	// address
	Address string `json:"address,omitempty"`

	// network id
	NetworkID int64 `json:"network_id,omitempty"`

	// pref
	Pref int64 `json:"pref,omitempty"`

	// tenant id
	TenantID int64 `json:"tenant_id,omitempty"`
}

// Validate validates this networkrouter input
func (m *NetworkrouterInput) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
