package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// NodeOutput node output
// swagger:model node-output
type NodeOutput struct {

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// updated at
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	NodeInput
}

// Validate validates this node output
func (m *NodeOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.NodeInput.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NodeOutput) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}
