package dnsnamefilters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETEDnsnamefiltersReader is a Reader for the DELETEDnsnamefilters structure.
type DELETEDnsnamefiltersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEDnsnamefiltersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETEDnsnamefiltersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEDnsnamefiltersNoContent creates a DELETEDnsnamefiltersNoContent with default headers values
func NewDELETEDnsnamefiltersNoContent() *DELETEDnsnamefiltersNoContent {
	return &DELETEDnsnamefiltersNoContent{}
}

/*DELETEDnsnamefiltersNoContent handles this case with default header values.

DELETEDnsnamefiltersNoContent d e l e t e dnsnamefilters no content
*/
type DELETEDnsnamefiltersNoContent struct {
}

func (o *DELETEDnsnamefiltersNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dnsnamefilters/{id}][%d] dELETEDnsnamefiltersNoContent ", 204)
}

func (o *DELETEDnsnamefiltersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
