package dnsnamefilters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEDnsnamefiltersParams creates a new DELETEDnsnamefiltersParams object
// with the default values initialized.
func NewDELETEDnsnamefiltersParams() *DELETEDnsnamefiltersParams {
	var ()
	return &DELETEDnsnamefiltersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEDnsnamefiltersParamsWithTimeout creates a new DELETEDnsnamefiltersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEDnsnamefiltersParamsWithTimeout(timeout time.Duration) *DELETEDnsnamefiltersParams {
	var ()
	return &DELETEDnsnamefiltersParams{

		timeout: timeout,
	}
}

// NewDELETEDnsnamefiltersParamsWithContext creates a new DELETEDnsnamefiltersParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEDnsnamefiltersParamsWithContext(ctx context.Context) *DELETEDnsnamefiltersParams {
	var ()
	return &DELETEDnsnamefiltersParams{

		Context: ctx,
	}
}

/*DELETEDnsnamefiltersParams contains all the parameters to send to the API endpoint
for the d e l e t e dnsnamefilters operation typically these are written to a http.Request
*/
type DELETEDnsnamefiltersParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) WithTimeout(timeout time.Duration) *DELETEDnsnamefiltersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) WithContext(ctx context.Context) *DELETEDnsnamefiltersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) WithID(id string) *DELETEDnsnamefiltersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e dnsnamefilters params
func (o *DELETEDnsnamefiltersParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEDnsnamefiltersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
