package dnsnamefilters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTDnsnamefiltersReader is a Reader for the POSTDnsnamefilters structure.
type POSTDnsnamefiltersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTDnsnamefiltersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTDnsnamefiltersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTDnsnamefiltersCreated creates a POSTDnsnamefiltersCreated with default headers values
func NewPOSTDnsnamefiltersCreated() *POSTDnsnamefiltersCreated {
	return &POSTDnsnamefiltersCreated{}
}

/*POSTDnsnamefiltersCreated handles this case with default header values.

POSTDnsnamefiltersCreated p o s t dnsnamefilters created
*/
type POSTDnsnamefiltersCreated struct {
	Payload *models.DnsnamefiltersOutput
}

func (o *POSTDnsnamefiltersCreated) Error() string {
	return fmt.Sprintf("[POST /dnsnamefilters][%d] pOSTDnsnamefiltersCreated  %+v", 201, o.Payload)
}

func (o *POSTDnsnamefiltersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DnsnamefiltersOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
