package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETENetworkrangeParams creates a new DELETENetworkrangeParams object
// with the default values initialized.
func NewDELETENetworkrangeParams() *DELETENetworkrangeParams {
	var ()
	return &DELETENetworkrangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETENetworkrangeParamsWithTimeout creates a new DELETENetworkrangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETENetworkrangeParamsWithTimeout(timeout time.Duration) *DELETENetworkrangeParams {
	var ()
	return &DELETENetworkrangeParams{

		timeout: timeout,
	}
}

// NewDELETENetworkrangeParamsWithContext creates a new DELETENetworkrangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETENetworkrangeParamsWithContext(ctx context.Context) *DELETENetworkrangeParams {
	var ()
	return &DELETENetworkrangeParams{

		Context: ctx,
	}
}

/*DELETENetworkrangeParams contains all the parameters to send to the API endpoint
for the d e l e t e networkrange operation typically these are written to a http.Request
*/
type DELETENetworkrangeParams struct {

	/*ID*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) WithTimeout(timeout time.Duration) *DELETENetworkrangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) WithContext(ctx context.Context) *DELETENetworkrangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) WithID(id string) *DELETENetworkrangeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e networkrange params
func (o *DELETENetworkrangeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETENetworkrangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
