package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETENetworkrangeReader is a Reader for the DELETENetworkrange structure.
type DELETENetworkrangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETENetworkrangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDELETENetworkrangeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETENetworkrangeNoContent creates a DELETENetworkrangeNoContent with default headers values
func NewDELETENetworkrangeNoContent() *DELETENetworkrangeNoContent {
	return &DELETENetworkrangeNoContent{}
}

/*DELETENetworkrangeNoContent handles this case with default header values.

DELETENetworkrangeNoContent d e l e t e networkrange no content
*/
type DELETENetworkrangeNoContent struct {
}

func (o *DELETENetworkrangeNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networkranges/{id}][%d] dELETENetworkrangeNoContent ", 204)
}

func (o *DELETENetworkrangeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
