package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// NewPOSTNetworkrangeParams creates a new POSTNetworkrangeParams object
// with the default values initialized.
func NewPOSTNetworkrangeParams() *POSTNetworkrangeParams {
	var ()
	return &POSTNetworkrangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTNetworkrangeParamsWithTimeout creates a new POSTNetworkrangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTNetworkrangeParamsWithTimeout(timeout time.Duration) *POSTNetworkrangeParams {
	var ()
	return &POSTNetworkrangeParams{

		timeout: timeout,
	}
}

// NewPOSTNetworkrangeParamsWithContext creates a new POSTNetworkrangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTNetworkrangeParamsWithContext(ctx context.Context) *POSTNetworkrangeParams {
	var ()
	return &POSTNetworkrangeParams{

		Context: ctx,
	}
}

/*POSTNetworkrangeParams contains all the parameters to send to the API endpoint
for the p o s t networkrange operation typically these are written to a http.Request
*/
type POSTNetworkrangeParams struct {

	/*Body*/
	Body *models.NetworkrangeInput

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the p o s t networkrange params
func (o *POSTNetworkrangeParams) WithTimeout(timeout time.Duration) *POSTNetworkrangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t networkrange params
func (o *POSTNetworkrangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t networkrange params
func (o *POSTNetworkrangeParams) WithContext(ctx context.Context) *POSTNetworkrangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t networkrange params
func (o *POSTNetworkrangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p o s t networkrange params
func (o *POSTNetworkrangeParams) WithBody(body *models.NetworkrangeInput) *POSTNetworkrangeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t networkrange params
func (o *POSTNetworkrangeParams) SetBody(body *models.NetworkrangeInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTNetworkrangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NetworkrangeInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
