package networkranges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalrebar/digitalrebar/go/rebar-core-api/models"
)

// POSTNetworkrangeReader is a Reader for the POSTNetworkrange structure.
type POSTNetworkrangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTNetworkrangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTNetworkrangeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTNetworkrangeCreated creates a POSTNetworkrangeCreated with default headers values
func NewPOSTNetworkrangeCreated() *POSTNetworkrangeCreated {
	return &POSTNetworkrangeCreated{}
}

/*POSTNetworkrangeCreated handles this case with default header values.

POSTNetworkrangeCreated p o s t networkrange created
*/
type POSTNetworkrangeCreated struct {
	Payload *models.NetworkrangeOutput
}

func (o *POSTNetworkrangeCreated) Error() string {
	return fmt.Sprintf("[POST /networkranges][%d] pOSTNetworkrangeCreated  %+v", 201, o.Payload)
}

func (o *POSTNetworkrangeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkrangeOutput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
